"""add_phase_2_fre_tables

Revision ID: 37116c79d2eb
Revises: d310fd13bdc4
Create Date: 2026-06-11 13:42:44.984522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37116c79d2eb'
down_revision: Union[str, None] = 'd310fd13bdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fre_capital_social_aumento_classes_acoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('tipo_classe_acao_preferencial', sa.String(length=255), nullable=False),
    sa.Column('quantidade_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', 'tipo_classe_acao_preferencial', name='uq_fre_cap_soc_aumento_classes_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_ano_origem'), 'fre_capital_social_aumento_classes_acoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_cnpj_companhia'), 'fre_capital_social_aumento_classes_acoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_companhia_id'), 'fre_capital_social_aumento_classes_acoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_data_referencia'), 'fre_capital_social_aumento_classes_acoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_id_capital_social'), 'fre_capital_social_aumento_classes_acoes', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_id_documento'), 'fre_capital_social_aumento_classes_acoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_tipo_classe_acao_preferencial'), 'fre_capital_social_aumento_classes_acoes', ['tipo_classe_acao_preferencial'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumento_classes_acoes_versao'), 'fre_capital_social_aumento_classes_acoes', ['versao'], unique=False)
    op.create_table('fre_capital_social_aumentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('data_deliberacao', sa.Date(), nullable=True),
    sa.Column('valor_aumento', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('origem_aumento', sa.String(length=255), nullable=True),
    sa.Column('quantidade_acoes_ordinarias', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_acoes_preferenciais', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_total_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', name='uq_fre_capital_social_aumentos_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_aumentos_ano_origem'), 'fre_capital_social_aumentos', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_cnpj_companhia'), 'fre_capital_social_aumentos', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_companhia_id'), 'fre_capital_social_aumentos', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_data_referencia'), 'fre_capital_social_aumentos', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_id_capital_social'), 'fre_capital_social_aumentos', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_id_documento'), 'fre_capital_social_aumentos', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_aumentos_versao'), 'fre_capital_social_aumentos', ['versao'], unique=False)
    op.create_table('fre_capital_social_desdobramento_classes_acoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('tipo_classe_acao_preferencial', sa.String(length=255), nullable=False),
    sa.Column('quantidade_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', 'tipo_classe_acao_preferencial', name='uq_fre_cap_soc_desdob_classes_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_ano_origem'), 'fre_capital_social_desdobramento_classes_acoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_cnpj_companhia'), 'fre_capital_social_desdobramento_classes_acoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_companhia_id'), 'fre_capital_social_desdobramento_classes_acoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_data_referencia'), 'fre_capital_social_desdobramento_classes_acoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_id_capital_social'), 'fre_capital_social_desdobramento_classes_acoes', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_id_documento'), 'fre_capital_social_desdobramento_classes_acoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_tipo_classe_acao_preferencial'), 'fre_capital_social_desdobramento_classes_acoes', ['tipo_classe_acao_preferencial'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_versao'), 'fre_capital_social_desdobramento_classes_acoes', ['versao'], unique=False)
    op.create_table('fre_capital_social_desdobramentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('data_deliberacao', sa.Date(), nullable=True),
    sa.Column('tipo_desdobramento', sa.String(length=255), nullable=True),
    sa.Column('proporcao_acoes_novas', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('proporcao_acoes_antigas', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_acoes_ordinarias', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_acoes_preferenciais', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_total_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', name='uq_fre_capital_social_desdobramentos_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_ano_origem'), 'fre_capital_social_desdobramentos', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_cnpj_companhia'), 'fre_capital_social_desdobramentos', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_companhia_id'), 'fre_capital_social_desdobramentos', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_data_referencia'), 'fre_capital_social_desdobramentos', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_id_capital_social'), 'fre_capital_social_desdobramentos', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_id_documento'), 'fre_capital_social_desdobramentos', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_desdobramentos_versao'), 'fre_capital_social_desdobramentos', ['versao'], unique=False)
    op.create_table('fre_capital_social_reducao_classes_acoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('tipo_classe_acao_preferencial', sa.String(length=255), nullable=False),
    sa.Column('quantidade_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', 'tipo_classe_acao_preferencial', name='uq_fre_cap_soc_reducao_classes_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_ano_origem'), 'fre_capital_social_reducao_classes_acoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_cnpj_companhia'), 'fre_capital_social_reducao_classes_acoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_companhia_id'), 'fre_capital_social_reducao_classes_acoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_data_referencia'), 'fre_capital_social_reducao_classes_acoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_id_capital_social'), 'fre_capital_social_reducao_classes_acoes', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_id_documento'), 'fre_capital_social_reducao_classes_acoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_tipo_classe_acao_preferencial'), 'fre_capital_social_reducao_classes_acoes', ['tipo_classe_acao_preferencial'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducao_classes_acoes_versao'), 'fre_capital_social_reducao_classes_acoes', ['versao'], unique=False)
    op.create_table('fre_capital_social_reducoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_capital_social', sa.Integer(), nullable=False),
    sa.Column('data_deliberacao', sa.Date(), nullable=True),
    sa.Column('valor_reducao', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('motivo_reducao', sa.Text(), nullable=True),
    sa.Column('quantidade_acoes_ordinarias', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_acoes_preferenciais', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_total_acoes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_capital_social', name='uq_fre_capital_social_reducoes_chave_natural')
    )
    op.create_index(op.f('ix_fre_capital_social_reducoes_ano_origem'), 'fre_capital_social_reducoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_cnpj_companhia'), 'fre_capital_social_reducoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_companhia_id'), 'fre_capital_social_reducoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_data_referencia'), 'fre_capital_social_reducoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_id_capital_social'), 'fre_capital_social_reducoes', ['id_capital_social'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_id_documento'), 'fre_capital_social_reducoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_capital_social_reducoes_versao'), 'fre_capital_social_reducoes', ['versao'], unique=False)
    op.create_table('fre_direitos_acoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('tipo_classe_acao', sa.String(length=255), nullable=False),
    sa.Column('direito_voto', sa.String(length=255), nullable=False),
    sa.Column('outros_direitos', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'tipo_classe_acao', 'direito_voto', name='uq_fre_direitos_acoes_chave_natural')
    )
    op.create_index(op.f('ix_fre_direitos_acoes_ano_origem'), 'fre_direitos_acoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_cnpj_companhia'), 'fre_direitos_acoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_companhia_id'), 'fre_direitos_acoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_data_referencia'), 'fre_direitos_acoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_direito_voto'), 'fre_direitos_acoes', ['direito_voto'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_id_documento'), 'fre_direitos_acoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_tipo_classe_acao'), 'fre_direitos_acoes', ['tipo_classe_acao'], unique=False)
    op.create_index(op.f('ix_fre_direitos_acoes_versao'), 'fre_direitos_acoes', ['versao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fre_direitos_acoes_versao'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_tipo_classe_acao'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_id_documento'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_direito_voto'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_data_referencia'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_companhia_id'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_cnpj_companhia'), table_name='fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_direitos_acoes_ano_origem'), table_name='fre_direitos_acoes')
    op.drop_table('fre_direitos_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_versao'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_id_documento'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_id_capital_social'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_data_referencia'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_companhia_id'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_cnpj_companhia'), table_name='fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducoes_ano_origem'), table_name='fre_capital_social_reducoes')
    op.drop_table('fre_capital_social_reducoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_versao'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_tipo_classe_acao_preferencial'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_id_documento'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_id_capital_social'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_data_referencia'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_companhia_id'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_cnpj_companhia'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_reducao_classes_acoes_ano_origem'), table_name='fre_capital_social_reducao_classes_acoes')
    op.drop_table('fre_capital_social_reducao_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_versao'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_id_documento'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_id_capital_social'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_data_referencia'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_companhia_id'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_cnpj_companhia'), table_name='fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramentos_ano_origem'), table_name='fre_capital_social_desdobramentos')
    op.drop_table('fre_capital_social_desdobramentos')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_versao'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_tipo_classe_acao_preferencial'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_id_documento'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_id_capital_social'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_data_referencia'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_companhia_id'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_cnpj_companhia'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_desdobramento_classes_acoes_ano_origem'), table_name='fre_capital_social_desdobramento_classes_acoes')
    op.drop_table('fre_capital_social_desdobramento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_versao'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_id_documento'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_id_capital_social'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_data_referencia'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_companhia_id'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_cnpj_companhia'), table_name='fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumentos_ano_origem'), table_name='fre_capital_social_aumentos')
    op.drop_table('fre_capital_social_aumentos')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_versao'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_tipo_classe_acao_preferencial'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_id_documento'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_id_capital_social'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_data_referencia'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_companhia_id'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_cnpj_companhia'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_index(op.f('ix_fre_capital_social_aumento_classes_acoes_ano_origem'), table_name='fre_capital_social_aumento_classes_acoes')
    op.drop_table('fre_capital_social_aumento_classes_acoes')
    # ### end Alembic commands ###
