"""add cgvn models

Revision ID: 4ecc5fa20efb
Revises: 9f3c2b1a4d5e
Create Date: 2026-06-08 20:12:14.382765
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ecc5fa20efb'
down_revision: str | None = '9f3c2b1a4d5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cgvn_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=True),
    sa.Column('codigo_cvm', sa.Integer(), nullable=True),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('data_inicio_exercicio_social', sa.Date(), nullable=True),
    sa.Column('data_fim_exercicio_social', sa.Date(), nullable=True),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('link_download', sa.String(length=1000), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('motivo_reapresentacao', sa.String(length=500), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'cnpj_companhia', 'codigo_cvm', 'data_referencia', 'versao',
        name='uq_cgvn_documentos_chave_alternativa'
    ),
    sa.UniqueConstraint('id_documento', 'versao', name='uq_cgvn_documentos_id_versao')
    )
    op.create_index(op.f('ix_cgvn_documentos_ano_origem'), 'cgvn_documentos', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_cnpj_companhia'), 'cgvn_documentos', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_codigo_cvm'), 'cgvn_documentos', ['codigo_cvm'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_companhia_id'), 'cgvn_documentos', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_data_entrega'), 'cgvn_documentos', ['data_entrega'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_data_referencia'), 'cgvn_documentos', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_id_documento'), 'cgvn_documentos', ['id_documento'], unique=False)
    op.create_index(op.f('ix_cgvn_documentos_versao'), 'cgvn_documentos', ['versao'], unique=False)
    op.create_table('cgvn_praticas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=True),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_item', sa.String(length=50), nullable=False),
    sa.Column('pratica_recomendada', sa.String(length=2000), nullable=True),
    sa.Column('pratica_adotada', sa.String(length=50), nullable=True),
    sa.Column('capitulo', sa.String(length=255), nullable=True),
    sa.Column('principio', sa.String(length=255), nullable=True),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'cnpj_companhia', 'data_referencia', 'versao', 'id_item', 'linha_origem',
        name='uq_cgvn_praticas_chave_natural'
    )
    )
    op.create_index(op.f('ix_cgvn_praticas_ano_origem'), 'cgvn_praticas', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_cnpj_companhia'), 'cgvn_praticas', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_companhia_id'), 'cgvn_praticas', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_data_referencia'), 'cgvn_praticas', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_id_documento'), 'cgvn_praticas', ['id_documento'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_id_item'), 'cgvn_praticas', ['id_item'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_pratica_adotada'), 'cgvn_praticas', ['pratica_adotada'], unique=False)
    op.create_index(op.f('ix_cgvn_praticas_versao'), 'cgvn_praticas', ['versao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cgvn_praticas_versao'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_pratica_adotada'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_id_item'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_id_documento'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_data_referencia'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_companhia_id'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_cnpj_companhia'), table_name='cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_praticas_ano_origem'), table_name='cgvn_praticas')
    op.drop_table('cgvn_praticas')
    op.drop_index(op.f('ix_cgvn_documentos_versao'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_id_documento'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_data_referencia'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_data_entrega'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_companhia_id'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_codigo_cvm'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_cnpj_companhia'), table_name='cgvn_documentos')
    op.drop_index(op.f('ix_cgvn_documentos_ano_origem'), table_name='cgvn_documentos')
    op.drop_table('cgvn_documentos')
    # ### end Alembic commands ###
