"""add_fre_administradores_declaracao_genero

Revision ID: 5fea16beb6da
Revises: 99959d6155e0
Create Date: 2026-06-11 14:33:37.808200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fea16beb6da'
down_revision: Union[str, None] = '99959d6155e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fre_administradores_declaracao_genero',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('orgao_administracao', sa.String(length=255), nullable=False),
    sa.Column('quantidade_feminino', sa.Integer(), nullable=True),
    sa.Column('quantidade_masculino', sa.Integer(), nullable=True),
    sa.Column('quantidade_nao_binario', sa.Integer(), nullable=True),
    sa.Column('quantidade_outros', sa.Integer(), nullable=True),
    sa.Column('quantidade_sem_resposta', sa.Integer(), nullable=True),
    sa.Column('nao_aplicavel', sa.Boolean(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'orgao_administracao', name='uq_fre_adm_dec_gen_chave_natural')
    )
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_ano_origem'), 'fre_administradores_declaracao_genero', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_cnpj_companhia'), 'fre_administradores_declaracao_genero', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_companhia_id'), 'fre_administradores_declaracao_genero', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_data_referencia'), 'fre_administradores_declaracao_genero', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_id_documento'), 'fre_administradores_declaracao_genero', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_orgao_administracao'), 'fre_administradores_declaracao_genero', ['orgao_administracao'], unique=False)
    op.create_index(op.f('ix_fre_administradores_declaracao_genero_versao'), 'fre_administradores_declaracao_genero', ['versao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_versao'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_orgao_administracao'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_id_documento'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_data_referencia'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_companhia_id'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_cnpj_companhia'), table_name='fre_administradores_declaracao_genero')
    op.drop_index(op.f('ix_fre_administradores_declaracao_genero_ano_origem'), table_name='fre_administradores_declaracao_genero')
    op.drop_table('fre_administradores_declaracao_genero')
    # ### end Alembic commands ###
