"""change_remuneracao_auditor_to_text

Revision ID: 603f55551d42
Revises: 6ab07a275eb0
Create Date: 2026-06-15 22:13:08.439760
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '603f55551d42'
down_revision: str | None = '6ab07a275eb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_auditores', 'remuneracao_auditor',
               existing_type=sa.NUMERIC(precision=38, scale=10),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_auditores', 'remuneracao_auditor',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###
