"""change_remuneracao_auditor_to_text

Revision ID: 603f55551d42
Revises: 6ab07a275eb0
Create Date: 2026-06-15 22:13:08.439760
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603f55551d42'
down_revision: Union[str, None] = '6ab07a275eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_auditores', 'remuneracao_auditor',
               existing_type=sa.NUMERIC(precision=38, scale=10),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_auditores', 'remuneracao_auditor',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###
