"""change_partes_relacionadas_numeric_to_text

Revision ID: 6ab07a275eb0
Revises: 6e7f8a9b0c1d
Create Date: 2026-06-15 22:00:19.607030
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab07a275eb0'
down_revision: Union[str, None] = '6e7f8a9b0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_transacoes_partes_relacionadas', 'saldo_existente',
               existing_type=sa.NUMERIC(precision=38, scale=10),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'montante_interesse_parte_relacionada',
               existing_type=sa.NUMERIC(precision=38, scale=10),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'taxa_juros',
               existing_type=sa.NUMERIC(precision=38, scale=10),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_transacoes_partes_relacionadas', 'taxa_juros',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'montante_interesse_parte_relacionada',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'saldo_existente',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###
