"""add_p3_fre_tables

Revision ID: 857dd2fcee79
Revises: 0009_ingestion_v2_quarantine
Create Date: 2026-06-08 15:15:57.456403
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "857dd2fcee79"
down_revision: str | None = "0009_ingestion_v2_quarantine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fre_acoes_entregues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("data_inicio_exercicio_social", sa.Date(), nullable=True),
        sa.Column("data_fim_exercicio_social", sa.Date(), nullable=True),
        sa.Column("orgao_administracao", sa.String(length=255), nullable=True),
        sa.Column("quantidade_total_membros", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("quantidade_membros_remunerados", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("quantidade_acoes", sa.Integer(), nullable=True),
        sa.Column("preco_medio_ponderado_aquisicao", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("preco_medio_ponderado_mercado", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("valor_diferenca_aquisicao_mercado", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "orgao_administracao",
            "data_inicio_exercicio_social",
            "data_fim_exercicio_social",
            name="uq_fre_acoes_entregues_natural",
        ),
    )
    op.create_index(op.f("ix_fre_acoes_entregues_ano_origem"), "fre_acoes_entregues", ["ano_origem"], unique=False)
    op.create_index(
        op.f("ix_fre_acoes_entregues_cnpj_companhia"), "fre_acoes_entregues", ["cnpj_companhia"], unique=False
    )
    op.create_index(op.f("ix_fre_acoes_entregues_companhia_id"), "fre_acoes_entregues", ["companhia_id"], unique=False)
    op.create_index(
        op.f("ix_fre_acoes_entregues_data_referencia"), "fre_acoes_entregues", ["data_referencia"], unique=False
    )
    op.create_index(op.f("ix_fre_acoes_entregues_id_documento"), "fre_acoes_entregues", ["id_documento"], unique=False)
    op.create_index(op.f("ix_fre_acoes_entregues_versao"), "fre_acoes_entregues", ["versao"], unique=False)
    op.create_table(
        "fre_capital_social_classes_acoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("id_capital_social", sa.Integer(), nullable=False),
        sa.Column("tipo_classe_acao_preferencial", sa.String(length=255), nullable=True),
        sa.Column("quantidade_acoes", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "id_capital_social",
            "tipo_classe_acao_preferencial",
            name="uq_fre_cap_social_classes_acoes_chave_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_ano_origem"),
        "fre_capital_social_classes_acoes",
        ["ano_origem"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_cnpj_companhia"),
        "fre_capital_social_classes_acoes",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_companhia_id"),
        "fre_capital_social_classes_acoes",
        ["companhia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_data_referencia"),
        "fre_capital_social_classes_acoes",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_id_capital_social"),
        "fre_capital_social_classes_acoes",
        ["id_capital_social"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_id_documento"),
        "fre_capital_social_classes_acoes",
        ["id_documento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_classes_acoes_versao"), "fre_capital_social_classes_acoes", ["versao"], unique=False
    )
    op.create_table(
        "fre_capital_social_titulos_conversiveis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("id_capital_social", sa.Integer(), nullable=False),
        sa.Column("titulo_conversivel_acao", sa.String(length=255), nullable=True),
        sa.Column("condicoes_conversao", sa.Text(), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "id_capital_social",
            "titulo_conversivel_acao",
            name="uq_fre_cap_social_tit_conv_chave_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_ano_origem"),
        "fre_capital_social_titulos_conversiveis",
        ["ano_origem"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_cnpj_companhia"),
        "fre_capital_social_titulos_conversiveis",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_companhia_id"),
        "fre_capital_social_titulos_conversiveis",
        ["companhia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_data_referencia"),
        "fre_capital_social_titulos_conversiveis",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_id_capital_social"),
        "fre_capital_social_titulos_conversiveis",
        ["id_capital_social"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_id_documento"),
        "fre_capital_social_titulos_conversiveis",
        ["id_documento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_versao"),
        "fre_capital_social_titulos_conversiveis",
        ["versao"],
        unique=False,
    )
    op.create_table(
        "fre_distribuicao_capital",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("data_ultima_assembleia", sa.Date(), nullable=True),
        sa.Column("quantidade_acoes_ordinarias_circulacao", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("percentual_acoes_ordinarias_circulacao", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("quantidade_acoes_preferenciais_circulacao", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("percentual_acoes_preferenciais_circulacao", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("quantidade_total_acoes_circulacao", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("percentual_total_acoes_circulacao", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("quantidade_acionistas_pf", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("quantidade_acionistas_pj", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column(
            "quantidade_acionistas_investidores_institucionais", sa.Numeric(precision=30, scale=6), nullable=True
        ),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            name="uq_fre_distribuicao_capital_chave_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_ano_origem"), "fre_distribuicao_capital", ["ano_origem"], unique=False
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_cnpj_companhia"), "fre_distribuicao_capital", ["cnpj_companhia"], unique=False
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_companhia_id"), "fre_distribuicao_capital", ["companhia_id"], unique=False
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_data_referencia"),
        "fre_distribuicao_capital",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_id_documento"), "fre_distribuicao_capital", ["id_documento"], unique=False
    )
    op.create_index(op.f("ix_fre_distribuicao_capital_versao"), "fre_distribuicao_capital", ["versao"], unique=False)
    op.create_table(
        "fre_distribuicao_capital_classes_acoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("classe_acoes_preferenciais", sa.String(length=255), nullable=True),
        sa.Column("sigla_classe_acoes_preferenciais", sa.String(length=50), nullable=True),
        sa.Column("quantidade_acoes_preferenciais_circulacao", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("percentual_acoes_preferenciais_circulacao", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "sigla_classe_acoes_preferenciais",
            name="uq_fre_dist_capital_classes_acoes_chave_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_ano_origem"),
        "fre_distribuicao_capital_classes_acoes",
        ["ano_origem"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_cnpj_companhia"),
        "fre_distribuicao_capital_classes_acoes",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_companhia_id"),
        "fre_distribuicao_capital_classes_acoes",
        ["companhia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_data_referencia"),
        "fre_distribuicao_capital_classes_acoes",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_id_documento"),
        "fre_distribuicao_capital_classes_acoes",
        ["id_documento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_versao"),
        "fre_distribuicao_capital_classes_acoes",
        ["versao"],
        unique=False,
    )
    op.create_table(
        "fre_posicoes_acionarias_classes_acoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("id_acionista", sa.Integer(), nullable=False),
        sa.Column("tipo_classe_acao_preferencial", sa.String(length=255), nullable=True),
        sa.Column("quantidade_acoes", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("percentual_acoes", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "id_acionista",
            "tipo_classe_acao_preferencial",
            name="uq_fre_posicoes_acionarias_classes_acoes_chave_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_ano_origem"),
        "fre_posicoes_acionarias_classes_acoes",
        ["ano_origem"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_cnpj_companhia"),
        "fre_posicoes_acionarias_classes_acoes",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_companhia_id"),
        "fre_posicoes_acionarias_classes_acoes",
        ["companhia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_data_referencia"),
        "fre_posicoes_acionarias_classes_acoes",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_id_acionista"),
        "fre_posicoes_acionarias_classes_acoes",
        ["id_acionista"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_id_documento"),
        "fre_posicoes_acionarias_classes_acoes",
        ["id_documento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_versao"),
        "fre_posicoes_acionarias_classes_acoes",
        ["versao"],
        unique=False,
    )
    op.create_table(
        "fre_remuneracoes_acoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("data_inicio_exercicio_social", sa.Date(), nullable=True),
        sa.Column("data_fim_exercicio_social", sa.Date(), nullable=True),
        sa.Column("orgao_administracao", sa.String(length=255), nullable=True),
        sa.Column("quantidade_total_membros", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("quantidade_membros_remunerados", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("preco_medio_ponderado_opcoes_em_aberto", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("preco_medio_ponderado_opcoes_exercidas", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("preco_medio_ponderado_opcoes_perdidas", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("diluicao_potencial", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "orgao_administracao",
            "data_inicio_exercicio_social",
            "data_fim_exercicio_social",
            name="uq_fre_remuneracoes_acoes_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_acoes_ano_origem"), "fre_remuneracoes_acoes", ["ano_origem"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_acoes_cnpj_companhia"), "fre_remuneracoes_acoes", ["cnpj_companhia"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_acoes_companhia_id"), "fre_remuneracoes_acoes", ["companhia_id"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_acoes_data_referencia"), "fre_remuneracoes_acoes", ["data_referencia"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_acoes_id_documento"), "fre_remuneracoes_acoes", ["id_documento"], unique=False
    )
    op.create_index(op.f("ix_fre_remuneracoes_acoes_versao"), "fre_remuneracoes_acoes", ["versao"], unique=False)
    op.create_table(
        "fre_remuneracoes_maximas_minimas_medias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("data_inicio_exercicio_social", sa.Date(), nullable=True),
        sa.Column("data_fim_exercicio_social", sa.Date(), nullable=True),
        sa.Column("orgao_administracao", sa.String(length=255), nullable=True),
        sa.Column("numero_membros", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("numero_membros_remunerados", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("valor_maior_remuneracao", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("valor_medio_remuneracao", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("valor_menor_remuneracao", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "orgao_administracao",
            "data_inicio_exercicio_social",
            "data_fim_exercicio_social",
            name="uq_fre_remun_max_min_med_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_ano_origem"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["ano_origem"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_cnpj_companhia"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_companhia_id"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["companhia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_data_referencia"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_id_documento"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["id_documento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_versao"),
        "fre_remuneracoes_maximas_minimas_medias",
        ["versao"],
        unique=False,
    )
    op.create_table(
        "fre_remuneracoes_variaveis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("data_inicio_exercicio_social", sa.Date(), nullable=True),
        sa.Column("data_fim_exercicio_social", sa.Date(), nullable=True),
        sa.Column("orgao_administracao", sa.String(length=255), nullable=True),
        sa.Column("quantidade_total_membros", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("quantidade_membros_remunerados", sa.Numeric(precision=30, scale=6), nullable=True),
        sa.Column("bonus_valor_minimo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("bonus_valor_maximo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("bonus_valor_metas_atingidas", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("bonus_valor_efetivo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("participacao_valor_minimo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("participacao_valor_maximo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("participacao_valor_metas_atingidas", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("participacao_valor_efetivo", sa.Numeric(precision=30, scale=10), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "orgao_administracao",
            "data_inicio_exercicio_social",
            "data_fim_exercicio_social",
            name="uq_fre_remuneracoes_variaveis_natural",
        ),
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_ano_origem"), "fre_remuneracoes_variaveis", ["ano_origem"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_cnpj_companhia"),
        "fre_remuneracoes_variaveis",
        ["cnpj_companhia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_companhia_id"), "fre_remuneracoes_variaveis", ["companhia_id"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_data_referencia"),
        "fre_remuneracoes_variaveis",
        ["data_referencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_id_documento"), "fre_remuneracoes_variaveis", ["id_documento"], unique=False
    )
    op.create_index(
        op.f("ix_fre_remuneracoes_variaveis_versao"), "fre_remuneracoes_variaveis", ["versao"], unique=False
    )
    op.create_table(
        "fre_responsaveis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("companhia_id", sa.Uuid(), nullable=True),
        sa.Column("cnpj_companhia", sa.String(length=14), nullable=False),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("nome_companhia", sa.String(length=255), nullable=True),
        sa.Column("nome_responsavel", sa.String(length=255), nullable=True),
        sa.Column("cargo_responsavel", sa.String(length=1000), nullable=True),
        sa.Column("arquivo_origem", sa.String(length=255), nullable=False),
        sa.Column("ano_origem", sa.Integer(), nullable=True),
        sa.Column("linha_origem", sa.Integer(), nullable=True),
        sa.Column("hash_origem", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sincronizado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("alterado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["companhia_id"],
            ["companhias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_documento",
            "versao",
            "data_referencia",
            "cnpj_companhia",
            "nome_responsavel",
            "cargo_responsavel",
            name="uq_fre_responsaveis_chave_natural",
        ),
    )
    op.create_index(op.f("ix_fre_responsaveis_ano_origem"), "fre_responsaveis", ["ano_origem"], unique=False)
    op.create_index(op.f("ix_fre_responsaveis_cnpj_companhia"), "fre_responsaveis", ["cnpj_companhia"], unique=False)
    op.create_index(op.f("ix_fre_responsaveis_companhia_id"), "fre_responsaveis", ["companhia_id"], unique=False)
    op.create_index(op.f("ix_fre_responsaveis_data_referencia"), "fre_responsaveis", ["data_referencia"], unique=False)
    op.create_index(op.f("ix_fre_responsaveis_id_documento"), "fre_responsaveis", ["id_documento"], unique=False)
    op.create_index(op.f("ix_fre_responsaveis_versao"), "fre_responsaveis", ["versao"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_fre_responsaveis_versao"), table_name="fre_responsaveis")
    op.drop_index(op.f("ix_fre_responsaveis_id_documento"), table_name="fre_responsaveis")
    op.drop_index(op.f("ix_fre_responsaveis_data_referencia"), table_name="fre_responsaveis")
    op.drop_index(op.f("ix_fre_responsaveis_companhia_id"), table_name="fre_responsaveis")
    op.drop_index(op.f("ix_fre_responsaveis_cnpj_companhia"), table_name="fre_responsaveis")
    op.drop_index(op.f("ix_fre_responsaveis_ano_origem"), table_name="fre_responsaveis")
    op.drop_table("fre_responsaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_versao"), table_name="fre_remuneracoes_variaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_id_documento"), table_name="fre_remuneracoes_variaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_data_referencia"), table_name="fre_remuneracoes_variaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_companhia_id"), table_name="fre_remuneracoes_variaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_cnpj_companhia"), table_name="fre_remuneracoes_variaveis")
    op.drop_index(op.f("ix_fre_remuneracoes_variaveis_ano_origem"), table_name="fre_remuneracoes_variaveis")
    op.drop_table("fre_remuneracoes_variaveis")
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_versao"), table_name="fre_remuneracoes_maximas_minimas_medias"
    )
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_id_documento"),
        table_name="fre_remuneracoes_maximas_minimas_medias",
    )
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_data_referencia"),
        table_name="fre_remuneracoes_maximas_minimas_medias",
    )
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_companhia_id"),
        table_name="fre_remuneracoes_maximas_minimas_medias",
    )
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_cnpj_companhia"),
        table_name="fre_remuneracoes_maximas_minimas_medias",
    )
    op.drop_index(
        op.f("ix_fre_remuneracoes_maximas_minimas_medias_ano_origem"),
        table_name="fre_remuneracoes_maximas_minimas_medias",
    )
    op.drop_table("fre_remuneracoes_maximas_minimas_medias")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_versao"), table_name="fre_remuneracoes_acoes")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_id_documento"), table_name="fre_remuneracoes_acoes")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_data_referencia"), table_name="fre_remuneracoes_acoes")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_companhia_id"), table_name="fre_remuneracoes_acoes")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_cnpj_companhia"), table_name="fre_remuneracoes_acoes")
    op.drop_index(op.f("ix_fre_remuneracoes_acoes_ano_origem"), table_name="fre_remuneracoes_acoes")
    op.drop_table("fre_remuneracoes_acoes")
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_versao"), table_name="fre_posicoes_acionarias_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_id_documento"),
        table_name="fre_posicoes_acionarias_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_id_acionista"),
        table_name="fre_posicoes_acionarias_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_data_referencia"),
        table_name="fre_posicoes_acionarias_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_companhia_id"),
        table_name="fre_posicoes_acionarias_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_cnpj_companhia"),
        table_name="fre_posicoes_acionarias_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_posicoes_acionarias_classes_acoes_ano_origem"), table_name="fre_posicoes_acionarias_classes_acoes"
    )
    op.drop_table("fre_posicoes_acionarias_classes_acoes")
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_versao"), table_name="fre_distribuicao_capital_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_id_documento"),
        table_name="fre_distribuicao_capital_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_data_referencia"),
        table_name="fre_distribuicao_capital_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_companhia_id"),
        table_name="fre_distribuicao_capital_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_cnpj_companhia"),
        table_name="fre_distribuicao_capital_classes_acoes",
    )
    op.drop_index(
        op.f("ix_fre_distribuicao_capital_classes_acoes_ano_origem"),
        table_name="fre_distribuicao_capital_classes_acoes",
    )
    op.drop_table("fre_distribuicao_capital_classes_acoes")
    op.drop_index(op.f("ix_fre_distribuicao_capital_versao"), table_name="fre_distribuicao_capital")
    op.drop_index(op.f("ix_fre_distribuicao_capital_id_documento"), table_name="fre_distribuicao_capital")
    op.drop_index(op.f("ix_fre_distribuicao_capital_data_referencia"), table_name="fre_distribuicao_capital")
    op.drop_index(op.f("ix_fre_distribuicao_capital_companhia_id"), table_name="fre_distribuicao_capital")
    op.drop_index(op.f("ix_fre_distribuicao_capital_cnpj_companhia"), table_name="fre_distribuicao_capital")
    op.drop_index(op.f("ix_fre_distribuicao_capital_ano_origem"), table_name="fre_distribuicao_capital")
    op.drop_table("fre_distribuicao_capital")
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_versao"), table_name="fre_capital_social_titulos_conversiveis"
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_id_documento"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_id_capital_social"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_data_referencia"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_companhia_id"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_cnpj_companhia"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_index(
        op.f("ix_fre_capital_social_titulos_conversiveis_ano_origem"),
        table_name="fre_capital_social_titulos_conversiveis",
    )
    op.drop_table("fre_capital_social_titulos_conversiveis")
    op.drop_index(op.f("ix_fre_capital_social_classes_acoes_versao"), table_name="fre_capital_social_classes_acoes")
    op.drop_index(
        op.f("ix_fre_capital_social_classes_acoes_id_documento"), table_name="fre_capital_social_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_capital_social_classes_acoes_id_capital_social"), table_name="fre_capital_social_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_capital_social_classes_acoes_data_referencia"), table_name="fre_capital_social_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_capital_social_classes_acoes_companhia_id"), table_name="fre_capital_social_classes_acoes"
    )
    op.drop_index(
        op.f("ix_fre_capital_social_classes_acoes_cnpj_companhia"), table_name="fre_capital_social_classes_acoes"
    )
    op.drop_index(op.f("ix_fre_capital_social_classes_acoes_ano_origem"), table_name="fre_capital_social_classes_acoes")
    op.drop_table("fre_capital_social_classes_acoes")
    op.drop_index(op.f("ix_fre_acoes_entregues_versao"), table_name="fre_acoes_entregues")
    op.drop_index(op.f("ix_fre_acoes_entregues_id_documento"), table_name="fre_acoes_entregues")
    op.drop_index(op.f("ix_fre_acoes_entregues_data_referencia"), table_name="fre_acoes_entregues")
    op.drop_index(op.f("ix_fre_acoes_entregues_companhia_id"), table_name="fre_acoes_entregues")
    op.drop_index(op.f("ix_fre_acoes_entregues_cnpj_companhia"), table_name="fre_acoes_entregues")
    op.drop_index(op.f("ix_fre_acoes_entregues_ano_origem"), table_name="fre_acoes_entregues")
    op.drop_table("fre_acoes_entregues")
    # ### end Alembic commands ###
