"""alter_fre_models_string_to_text

Revision ID: 9337421f6958
Revises: f080f52966a3
Create Date: 2026-06-11 14:54:04.883266
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9337421f6958'
down_revision: Union[str, None] = 'f080f52966a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_acoes_entregues', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_acoes_entregues', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_acoes_entregues', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_administradores_declaracao_genero', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_declaracao_genero', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_administradores_declaracao_genero', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'profissao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'cargo_eletivo_ocupado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'complemento_cargo_eletivo_ocupado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'prazo_mandato',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_auditores', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'auditor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'tipo_origem_auditor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'tipo_capital',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'prazo_integralizacao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumentos', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumentos', 'origem_aumento',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumentos', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramentos', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramentos', 'tipo_desdobramento',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramentos', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_reducoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'titulo_conversivel_acao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_direitos_acoes', 'tipo_classe_acao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'direito_voto',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_distribuicao_capital', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'classe_acoes_preferenciais',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_documentos', 'denominacao_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'categoria_documento',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'link_documento',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_empregados_posicao_genero', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_empregados_posicao_genero', 'posicao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_empregados_posicao_genero', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_membros_comites', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_membros_comites', 'profissao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'tipo_comite',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'cargo_ocupado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'prazo_mandato',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_mercados_estrangeiros', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_mercados_estrangeiros', 'nome_mercado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_mercados_estrangeiros', 'orgao_regulador',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_mercados_estrangeiros', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_outros_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_outros_valores_mobiliarios', 'nome_valor_mobiliario',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_outros_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_plano_recompra_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_plano_recompra_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_plano_recompra_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_planos_recompra', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_planos_recompra', 'limite_prazo_aquisicao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_planos_recompra', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_posicoes_acionarias', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'acionista',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_acionista',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'acionista_relacionado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_acionista_relacionado',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'nacionalidade',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'representante_legal',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_representante_legal',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_administrador',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'nome_emissor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'cargo_administrador',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'nome_emissor_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'cargo_Pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'tipo_parentesco',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'nome_administrador',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'cargo_administrador',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'nome_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'tipo_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'cargo_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'categoria_pessoa_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'tipo_relacao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_acoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_acoes', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_acoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_variaveis', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_variaveis', 'orgao_administracao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_variaveis', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_responsaveis', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'nome_responsavel',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'cargo_responsavel',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_titulares_valores_mobiliarios', 'nome_titular',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'classe_valor_mobiliario',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_titulos_exterior', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_titulos_exterior', 'nome_titulo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_titulos_exterior', 'pais_emissao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_titulos_exterior', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_transacoes_partes_relacionadas', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'tipo_pessoa',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'classe_valor_mobiliario',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'natureza_movimentacao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'classe_valor_mobiliario',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'historico_exercicio',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_volumes_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_volumes_valores_mobiliarios', 'classe_valor_mobiliario',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_volumes_valores_mobiliarios', 'sigla_classe_acoes_preferenciais',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_volumes_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_volumes_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_volumes_valores_mobiliarios', 'sigla_classe_acoes_preferenciais',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_volumes_valores_mobiliarios', 'classe_valor_mobiliario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_volumes_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'historico_exercicio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'classe_valor_mobiliario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_ultimos_exercicios', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'natureza_movimentacao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'classe_valor_mobiliario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_valores_mobiliarios_tesouraria_movimentacoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_transacoes_partes_relacionadas', 'tipo_pessoa',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_titulos_exterior', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_titulos_exterior', 'pais_emissao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_titulos_exterior', 'nome_titulo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_titulos_exterior', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_titulares_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'classe_valor_mobiliario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'nome_titular',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_titulares_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_responsaveis', 'cargo_responsavel',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'nome_responsavel',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_responsaveis', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_variaveis', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_variaveis', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_variaveis', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_totais_orgaos', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_maximas_minimas_medias', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_remuneracoes_acoes', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'tipo_relacao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'categoria_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'cargo_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'tipo_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'nome_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'cargo_administrador',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_subordinacao', 'nome_administrador',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_subordinacao', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'tipo_parentesco',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'cargo_Pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_emissor_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_pessoa_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'cargo_administrador',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_emissor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_relacoes_familiares', 'nome_administrador',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_relacoes_familiares', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_representante_legal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'representante_legal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'nacionalidade',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_acionista_relacionado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'acionista_relacionado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'tipo_pessoa_acionista',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'acionista',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_planos_recompra', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_planos_recompra', 'limite_prazo_aquisicao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_planos_recompra', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_plano_recompra_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_plano_recompra_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_plano_recompra_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_outros_valores_mobiliarios', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_outros_valores_mobiliarios', 'nome_valor_mobiliario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_outros_valores_mobiliarios', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_mercados_estrangeiros', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_mercados_estrangeiros', 'orgao_regulador',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_mercados_estrangeiros', 'nome_mercado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_mercados_estrangeiros', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_membros_comites', 'prazo_mandato',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'cargo_ocupado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'tipo_comite',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'profissao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_membros_comites', 'nome',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_membros_comites', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_empregados_posicao_genero', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_empregados_posicao_genero', 'posicao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_empregados_posicao_genero', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_documentos', 'link_documento',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'categoria_documento',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_documentos', 'denominacao_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'classe_acoes_preferenciais',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_distribuicao_capital', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_direitos_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'direito_voto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'tipo_classe_acao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_direitos_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'titulo_conversivel_acao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_titulos_conversiveis', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_reducoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_reducao_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramentos', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramentos', 'tipo_desdobramento',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramentos', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_desdobramento_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumentos', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumentos', 'origem_aumento',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumentos', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'tipo_classe_acao_preferencial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social_aumento_classes_acoes', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_capital_social', 'prazo_integralizacao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'tipo_capital',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_capital_social', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_auditores', 'tipo_origem_auditor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'auditor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_auditores', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'prazo_mandato',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'complemento_cargo_eletivo_ocupado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'cargo_eletivo_ocupado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'profissao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'nome',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_membros_conselho_fiscal', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_administradores_declaracao_genero', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_administradores_declaracao_genero', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_administradores_declaracao_genero', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_acoes_entregues', 'arquivo_origem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('fre_acoes_entregues', 'orgao_administracao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_acoes_entregues', 'nome_companhia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
