"""add_phase_3_fre_tables

Revision ID: 99959d6155e0
Revises: 37116c79d2eb
Create Date: 2026-06-11 13:50:07.220742
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99959d6155e0'
down_revision: Union[str, None] = '37116c79d2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fre_mercados_estrangeiros',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome_mercado', sa.String(length=255), nullable=False),
    sa.Column('orgao_regulador', sa.String(length=255), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_mercado', name='uq_fre_mercados_estrangeiros_chave_natural')
    )
    op.create_index(op.f('ix_fre_mercados_estrangeiros_ano_origem'), 'fre_mercados_estrangeiros', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_cnpj_companhia'), 'fre_mercados_estrangeiros', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_companhia_id'), 'fre_mercados_estrangeiros', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_data_referencia'), 'fre_mercados_estrangeiros', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_id_documento'), 'fre_mercados_estrangeiros', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_nome_mercado'), 'fre_mercados_estrangeiros', ['nome_mercado'], unique=False)
    op.create_index(op.f('ix_fre_mercados_estrangeiros_versao'), 'fre_mercados_estrangeiros', ['versao'], unique=False)
    op.create_table('fre_outros_valores_mobiliarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome_valor_mobiliario', sa.String(length=255), nullable=False),
    sa.Column('caracteristicas_valor_mobiliario', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_valor_mobiliario', name='uq_fre_outros_val_mob_chave_natural')
    )
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_ano_origem'), 'fre_outros_valores_mobiliarios', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_cnpj_companhia'), 'fre_outros_valores_mobiliarios', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_companhia_id'), 'fre_outros_valores_mobiliarios', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_data_referencia'), 'fre_outros_valores_mobiliarios', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_id_documento'), 'fre_outros_valores_mobiliarios', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_nome_valor_mobiliario'), 'fre_outros_valores_mobiliarios', ['nome_valor_mobiliario'], unique=False)
    op.create_index(op.f('ix_fre_outros_valores_mobiliarios_versao'), 'fre_outros_valores_mobiliarios', ['versao'], unique=False)
    op.create_table('fre_plano_recompra_classes_acoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_plano_recompra', sa.Integer(), nullable=False),
    sa.Column('tipo_classe_acao_preferencial', sa.String(length=255), nullable=False),
    sa.Column('quantidade_acoes_adquiridas', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_plano_recompra', 'tipo_classe_acao_preferencial', name='uq_fre_plano_recompra_classes_chave_natural')
    )
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_ano_origem'), 'fre_plano_recompra_classes_acoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_cnpj_companhia'), 'fre_plano_recompra_classes_acoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_companhia_id'), 'fre_plano_recompra_classes_acoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_data_referencia'), 'fre_plano_recompra_classes_acoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_id_documento'), 'fre_plano_recompra_classes_acoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_id_plano_recompra'), 'fre_plano_recompra_classes_acoes', ['id_plano_recompra'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_tipo_classe_acao_preferencial'), 'fre_plano_recompra_classes_acoes', ['tipo_classe_acao_preferencial'], unique=False)
    op.create_index(op.f('ix_fre_plano_recompra_classes_acoes_versao'), 'fre_plano_recompra_classes_acoes', ['versao'], unique=False)
    op.create_table('fre_planos_recompra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('id_plano_recompra', sa.Integer(), nullable=False),
    sa.Column('data_deliberacao', sa.Date(), nullable=True),
    sa.Column('objetivo_plano', sa.Text(), nullable=True),
    sa.Column('limite_prazo_aquisicao', sa.String(length=255), nullable=True),
    sa.Column('quantidade_total_ordinarias_adquiridas', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quantidade_total_preferenciais_adquiridas', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'id_plano_recompra', name='uq_fre_planos_recompra_chave_natural')
    )
    op.create_index(op.f('ix_fre_planos_recompra_ano_origem'), 'fre_planos_recompra', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_cnpj_companhia'), 'fre_planos_recompra', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_companhia_id'), 'fre_planos_recompra', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_data_referencia'), 'fre_planos_recompra', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_id_documento'), 'fre_planos_recompra', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_id_plano_recompra'), 'fre_planos_recompra', ['id_plano_recompra'], unique=False)
    op.create_index(op.f('ix_fre_planos_recompra_versao'), 'fre_planos_recompra', ['versao'], unique=False)
    op.create_table('fre_titulares_valores_mobiliarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome_titular', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj_titular', sa.String(length=20), nullable=True),
    sa.Column('classe_valor_mobiliario', sa.String(length=255), nullable=False),
    sa.Column('quantidade_valores_mobiliarios', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('percentual_classe', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_titular', 'classe_valor_mobiliario', name='uq_fre_titulares_val_mob_chave_natural')
    )
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_ano_origem'), 'fre_titulares_valores_mobiliarios', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_classe_valor_mobiliario'), 'fre_titulares_valores_mobiliarios', ['classe_valor_mobiliario'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_cnpj_companhia'), 'fre_titulares_valores_mobiliarios', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_companhia_id'), 'fre_titulares_valores_mobiliarios', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_data_referencia'), 'fre_titulares_valores_mobiliarios', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_id_documento'), 'fre_titulares_valores_mobiliarios', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_nome_titular'), 'fre_titulares_valores_mobiliarios', ['nome_titular'], unique=False)
    op.create_index(op.f('ix_fre_titulares_valores_mobiliarios_versao'), 'fre_titulares_valores_mobiliarios', ['versao'], unique=False)
    op.create_table('fre_titulos_exterior',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome_titulo', sa.String(length=255), nullable=False),
    sa.Column('pais_emissao', sa.String(length=255), nullable=True),
    sa.Column('caracteristicas', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_titulo', name='uq_fre_titulos_exterior_chave_natural')
    )
    op.create_index(op.f('ix_fre_titulos_exterior_ano_origem'), 'fre_titulos_exterior', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_cnpj_companhia'), 'fre_titulos_exterior', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_companhia_id'), 'fre_titulos_exterior', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_data_referencia'), 'fre_titulos_exterior', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_id_documento'), 'fre_titulos_exterior', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_nome_titulo'), 'fre_titulos_exterior', ['nome_titulo'], unique=False)
    op.create_index(op.f('ix_fre_titulos_exterior_versao'), 'fre_titulos_exterior', ['versao'], unique=False)
    op.create_table('fre_valores_mobiliarios_tesouraria_movimentacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('classe_valor_mobiliario', sa.String(length=255), nullable=False),
    sa.Column('data_movimentacao', sa.Date(), nullable=False),
    sa.Column('quantidade_movimentada', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('natureza_movimentacao', sa.String(length=255), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'classe_valor_mobiliario', 'data_movimentacao', name='uq_fre_val_mob_tes_mov_chave_natural')
    )
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_ano_origem'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_classe_valor_mobiliario'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['classe_valor_mobiliario'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_cnpj_companhia'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_companhia_id'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_data_movimentacao'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['data_movimentacao'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_data_referencia'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_id_documento'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_versao'), 'fre_valores_mobiliarios_tesouraria_movimentacoes', ['versao'], unique=False)
    op.create_table('fre_valores_mobiliarios_tesouraria_ultimos_exercicios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('classe_valor_mobiliario', sa.String(length=255), nullable=False),
    sa.Column('historico_exercicio', sa.String(length=255), nullable=False),
    sa.Column('quantidade_acoes_tesouraria', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'classe_valor_mobiliario', 'historico_exercicio', name='uq_fre_val_mob_tes_ult_ex_chave_natural')
    )
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_data_referencia'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_cnpj_companhia'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_companhia_id'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_historico_exercicio'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['historico_exercicio'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_classe_valor_mobiliario'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['classe_valor_mobiliario'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_ano_origem'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_id_documento'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_versao'), 'fre_valores_mobiliarios_tesouraria_ultimos_exercicios', ['versao'], unique=False)
    op.create_table('fre_volumes_valores_mobiliarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('classe_valor_mobiliario', sa.String(length=255), nullable=False),
    sa.Column('sigla_classe_acoes_preferenciais', sa.String(length=100), nullable=True),
    sa.Column('volume_negociacao', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'classe_valor_mobiliario', name='uq_fre_vol_val_mob_chave_natural')
    )
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_ano_origem'), 'fre_volumes_valores_mobiliarios', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_classe_valor_mobiliario'), 'fre_volumes_valores_mobiliarios', ['classe_valor_mobiliario'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_cnpj_companhia'), 'fre_volumes_valores_mobiliarios', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_companhia_id'), 'fre_volumes_valores_mobiliarios', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_data_referencia'), 'fre_volumes_valores_mobiliarios', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_id_documento'), 'fre_volumes_valores_mobiliarios', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_volumes_valores_mobiliarios_versao'), 'fre_volumes_valores_mobiliarios', ['versao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_versao'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_id_documento'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_data_referencia'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_companhia_id'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_cnpj_companhia'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_classe_valor_mobiliario'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_volumes_valores_mobiliarios_ano_origem'), table_name='fre_volumes_valores_mobiliarios')
    op.drop_table('fre_volumes_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_versao'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_id_documento'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_ano_origem'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_classe_valor_mobiliario'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_historico_exercicio'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_companhia_id'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_cnpj_companhia'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_ultimos_exercicios_data_referencia'), table_name='fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_table('fre_valores_mobiliarios_tesouraria_ultimos_exercicios')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_versao'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_id_documento'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_data_referencia'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_data_movimentacao'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_companhia_id'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_cnpj_companhia'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_classe_valor_mobiliario'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_valores_mobiliarios_tesouraria_movimentacoes_ano_origem'), table_name='fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_table('fre_valores_mobiliarios_tesouraria_movimentacoes')
    op.drop_index(op.f('ix_fre_titulos_exterior_versao'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_nome_titulo'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_id_documento'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_data_referencia'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_companhia_id'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_cnpj_companhia'), table_name='fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulos_exterior_ano_origem'), table_name='fre_titulos_exterior')
    op.drop_table('fre_titulos_exterior')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_versao'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_nome_titular'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_id_documento'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_data_referencia'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_companhia_id'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_cnpj_companhia'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_classe_valor_mobiliario'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_titulares_valores_mobiliarios_ano_origem'), table_name='fre_titulares_valores_mobiliarios')
    op.drop_table('fre_titulares_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_planos_recompra_versao'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_id_plano_recompra'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_id_documento'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_data_referencia'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_companhia_id'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_cnpj_companhia'), table_name='fre_planos_recompra')
    op.drop_index(op.f('ix_fre_planos_recompra_ano_origem'), table_name='fre_planos_recompra')
    op.drop_table('fre_planos_recompra')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_versao'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_tipo_classe_acao_preferencial'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_id_plano_recompra'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_id_documento'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_data_referencia'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_companhia_id'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_cnpj_companhia'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_plano_recompra_classes_acoes_ano_origem'), table_name='fre_plano_recompra_classes_acoes')
    op.drop_table('fre_plano_recompra_classes_acoes')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_versao'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_nome_valor_mobiliario'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_id_documento'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_data_referencia'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_companhia_id'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_cnpj_companhia'), table_name='fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_outros_valores_mobiliarios_ano_origem'), table_name='fre_outros_valores_mobiliarios')
    op.drop_table('fre_outros_valores_mobiliarios')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_versao'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_nome_mercado'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_id_documento'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_data_referencia'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_companhia_id'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_cnpj_companhia'), table_name='fre_mercados_estrangeiros')
    op.drop_index(op.f('ix_fre_mercados_estrangeiros_ano_origem'), table_name='fre_mercados_estrangeiros')
    op.drop_table('fre_mercados_estrangeiros')
    # ### end Alembic commands ###
