"""expand_fre_admin_membro_conselho_natural_key

Revision ID: cfcc31a7815b
Revises: 603f55551d42
Create Date: 2026-06-15 22:28:59.456179
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cfcc31a7815b'
down_revision: str | None = '603f55551d42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_fre_admin_memb_cons_fisc_chave_natural'), 'fre_administradores_membros_conselho_fiscal', type_='unique')
    op.create_unique_constraint('uq_fre_admin_memb_cons_fisc_chave_natural', 'fre_administradores_membros_conselho_fiscal', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome', 'cpf', 'orgao_administracao', 'data_eleicao', 'data_posse', 'cargo_eletivo_ocupado', 'outro_cargo_funcao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fre_admin_memb_cons_fisc_chave_natural', 'fre_administradores_membros_conselho_fiscal', type_='unique')
    op.create_unique_constraint(op.f('uq_fre_admin_memb_cons_fisc_chave_natural'), 'fre_administradores_membros_conselho_fiscal', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome', 'cpf', 'orgao_administracao', 'data_eleicao', 'data_posse'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
