"""add_phase_1_fre_tables

Revision ID: d310fd13bdc4
Revises: f484cf28f893
Create Date: 2026-06-11 13:31:10.361352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd310fd13bdc4'
down_revision: Union[str, None] = 'f484cf28f893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fre_administradores_membros_conselho_fiscal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('orgao_administracao', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('profissao', sa.String(length=255), nullable=True),
    sa.Column('cargo_eletivo_ocupado', sa.String(length=255), nullable=True),
    sa.Column('complemento_cargo_eletivo_ocupado', sa.String(length=255), nullable=True),
    sa.Column('data_eleicao', sa.Date(), nullable=True),
    sa.Column('data_posse', sa.Date(), nullable=True),
    sa.Column('data_inicio_primeiro_mandato', sa.Date(), nullable=True),
    sa.Column('prazo_mandato', sa.String(length=255), nullable=True),
    sa.Column('eleito_controlador', sa.String(length=50), nullable=True),
    sa.Column('outro_cargo_funcao', sa.Text(), nullable=True),
    sa.Column('experiencia_profissional', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_mandatos_consecutivos', sa.Integer(), nullable=True),
    sa.Column('percentual_participacao_reunioes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome', 'cpf', 'orgao_administracao', name='uq_fre_admin_memb_cons_fisc_chave_natural')
    )
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_ano_origem'), 'fre_administradores_membros_conselho_fiscal', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_cnpj_companhia'), 'fre_administradores_membros_conselho_fiscal', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_companhia_id'), 'fre_administradores_membros_conselho_fiscal', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_data_referencia'), 'fre_administradores_membros_conselho_fiscal', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_id_documento'), 'fre_administradores_membros_conselho_fiscal', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_nome'), 'fre_administradores_membros_conselho_fiscal', ['nome'], unique=False)
    op.create_index(op.f('ix_fre_administradores_membros_conselho_fiscal_versao'), 'fre_administradores_membros_conselho_fiscal', ['versao'], unique=False)
    op.create_table('fre_membros_comites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('profissao', sa.String(length=255), nullable=True),
    sa.Column('tipo_comite', sa.String(length=255), nullable=True),
    sa.Column('descricao_outros_comites', sa.Text(), nullable=True),
    sa.Column('cargo_ocupado', sa.String(length=255), nullable=True),
    sa.Column('descricao_outro_cargo_ocupado', sa.Text(), nullable=True),
    sa.Column('data_eleicao', sa.Date(), nullable=True),
    sa.Column('data_posse', sa.Date(), nullable=True),
    sa.Column('data_inicio_primeiro_mandato', sa.Date(), nullable=True),
    sa.Column('prazo_mandato', sa.String(length=255), nullable=True),
    sa.Column('outro_cargo_funcao', sa.Text(), nullable=True),
    sa.Column('experiencia_profissional', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_mandatos_consecutivos', sa.Integer(), nullable=True),
    sa.Column('percentual_participacao_reunioes', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome', 'cpf', 'tipo_comite', name='uq_fre_membros_comites_chave_natural')
    )
    op.create_index(op.f('ix_fre_membros_comites_ano_origem'), 'fre_membros_comites', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_cnpj_companhia'), 'fre_membros_comites', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_companhia_id'), 'fre_membros_comites', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_data_referencia'), 'fre_membros_comites', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_id_documento'), 'fre_membros_comites', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_nome'), 'fre_membros_comites', ['nome'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_tipo_comite'), 'fre_membros_comites', ['tipo_comite'], unique=False)
    op.create_index(op.f('ix_fre_membros_comites_versao'), 'fre_membros_comites', ['versao'], unique=False)
    op.create_table('fre_relacoes_familiares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('nome_administrador', sa.String(length=255), nullable=False),
    sa.Column('cpf_administrador', sa.String(length=20), nullable=True),
    sa.Column('nome_emissor', sa.String(length=255), nullable=True),
    sa.Column('cnpj_emissor', sa.String(length=14), nullable=True),
    sa.Column('cargo_administrador', sa.String(length=255), nullable=True),
    sa.Column('nome_pessoa_relacionada', sa.String(length=255), nullable=False),
    sa.Column('cpf_pessoa_relacionada', sa.String(length=20), nullable=True),
    sa.Column('nome_emissor_pessoa_relacionada', sa.String(length=255), nullable=True),
    sa.Column('cnpj_emissor_pessoa_relacionada', sa.String(length=14), nullable=True),
    sa.Column('cargo_Pessoa_relacionada', sa.String(length=255), nullable=True),
    sa.Column('tipo_parentesco', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_parentesco', name='uq_fre_relacoes_familiares_chave_natural')
    )
    op.create_index(op.f('ix_fre_relacoes_familiares_ano_origem'), 'fre_relacoes_familiares', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_cnpj_companhia'), 'fre_relacoes_familiares', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_companhia_id'), 'fre_relacoes_familiares', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_data_referencia'), 'fre_relacoes_familiares', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_id_documento'), 'fre_relacoes_familiares', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_nome_administrador'), 'fre_relacoes_familiares', ['nome_administrador'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_nome_pessoa_relacionada'), 'fre_relacoes_familiares', ['nome_pessoa_relacionada'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_tipo_parentesco'), 'fre_relacoes_familiares', ['tipo_parentesco'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_familiares_versao'), 'fre_relacoes_familiares', ['versao'], unique=False)
    op.create_table('fre_relacoes_subordinacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('data_inicio_exercicio_social', sa.Date(), nullable=True),
    sa.Column('data_fim_exercicio_social', sa.Date(), nullable=True),
    sa.Column('nome_administrador', sa.String(length=255), nullable=False),
    sa.Column('cpf_administrador', sa.String(length=20), nullable=True),
    sa.Column('cargo_administrador', sa.String(length=255), nullable=True),
    sa.Column('nome_pessoa_relacionada', sa.String(length=255), nullable=False),
    sa.Column('tipo_pessoa_relacionada', sa.String(length=100), nullable=True),
    sa.Column('documento_pessoa_relacionada', sa.String(length=20), nullable=True),
    sa.Column('cargo_pessoa_relacionada', sa.String(length=255), nullable=True),
    sa.Column('categoria_pessoa_relacionada', sa.String(length=255), nullable=True),
    sa.Column('tipo_relacao', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_relacao', name='uq_fre_relacoes_subordinacao_chave_natural')
    )
    op.create_index(op.f('ix_fre_relacoes_subordinacao_ano_origem'), 'fre_relacoes_subordinacao', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_cnpj_companhia'), 'fre_relacoes_subordinacao', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_companhia_id'), 'fre_relacoes_subordinacao', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_data_referencia'), 'fre_relacoes_subordinacao', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_id_documento'), 'fre_relacoes_subordinacao', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_nome_administrador'), 'fre_relacoes_subordinacao', ['nome_administrador'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_nome_pessoa_relacionada'), 'fre_relacoes_subordinacao', ['nome_pessoa_relacionada'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_tipo_relacao'), 'fre_relacoes_subordinacao', ['tipo_relacao'], unique=False)
    op.create_index(op.f('ix_fre_relacoes_subordinacao_versao'), 'fre_relacoes_subordinacao', ['versao'], unique=False)
    op.create_table('fre_transacoes_partes_relacionadas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('companhia_id', sa.Uuid(), nullable=True),
    sa.Column('cnpj_companhia', sa.String(length=14), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nome_companhia', sa.String(length=255), nullable=True),
    sa.Column('parte_relacionada', sa.String(length=255), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=100), nullable=True),
    sa.Column('documento_parte_relacionada', sa.String(length=20), nullable=True),
    sa.Column('relacao_emissor', sa.String(length=255), nullable=True),
    sa.Column('data_transacao', sa.Date(), nullable=True),
    sa.Column('objeto_contrato', sa.Text(), nullable=True),
    sa.Column('montante_envolvido', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('saldo_existente', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('montante_interesse_parte_relacionada', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('garantia_seguro', sa.Text(), nullable=True),
    sa.Column('duracao_transacao', sa.String(length=255), nullable=True),
    sa.Column('emprestimo_divida', sa.String(length=255), nullable=True),
    sa.Column('rescisao', sa.Text(), nullable=True),
    sa.Column('natureza_razao_operacao', sa.Text(), nullable=True),
    sa.Column('taxa_juros', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('posicao_contratual_emissor', sa.String(length=255), nullable=True),
    sa.Column('especificacao_posicao_contratual_emissor', sa.Text(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('ano_origem', sa.Integer(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('hash_origem', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['companhia_id'], ['companhias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'parte_relacionada', 'relacao_emissor', 'data_transacao', name='uq_fre_transacoes_partes_relac_chave_natural')
    )
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_ano_origem'), 'fre_transacoes_partes_relacionadas', ['ano_origem'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_cnpj_companhia'), 'fre_transacoes_partes_relacionadas', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_companhia_id'), 'fre_transacoes_partes_relacionadas', ['companhia_id'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_data_referencia'), 'fre_transacoes_partes_relacionadas', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_id_documento'), 'fre_transacoes_partes_relacionadas', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_parte_relacionada'), 'fre_transacoes_partes_relacionadas', ['parte_relacionada'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_relacao_emissor'), 'fre_transacoes_partes_relacionadas', ['relacao_emissor'], unique=False)
    op.create_index(op.f('ix_fre_transacoes_partes_relacionadas_versao'), 'fre_transacoes_partes_relacionadas', ['versao'], unique=False)
    op.drop_index(op.f('ix_companhia_identificadores_tipo'), table_name='companhia_identificadores')
    op.drop_index(op.f('ix_companhia_identificadores_valor_normalizado'), table_name='companhia_identificadores')
    op.drop_constraint(op.f('companhias_cnpj_companhia_key'), 'companhias', type_='unique')
    op.drop_constraint(op.f('companhias_codigo_cvm_key'), 'companhias', type_='unique')
    op.drop_index(op.f('ix_companhias_cnpj_companhia'), table_name='companhias')
    op.create_index(op.f('ix_companhias_cnpj_companhia'), 'companhias', ['cnpj_companhia'], unique=True)
    op.drop_index(op.f('ix_companhias_codigo_cvm'), table_name='companhias')
    op.create_index(op.f('ix_companhias_codigo_cvm'), 'companhias', ['codigo_cvm'], unique=True)
    op.drop_constraint(op.f('uq_ingestion_file_members_ingestion_file_id_member_name'), 'ingestion_file_members', type_='unique')
    op.drop_constraint(op.f('uq_ingestion_files_source_url_content_sha256'), 'ingestion_files', type_='unique')
    op.drop_constraint(op.f('uq_ingestion_rows_ingestion_file_member_id_linha_origem'), 'ingestion_rows', type_='unique')
    op.drop_constraint(op.f('uq_quarantine_items_ingestion_row_id'), 'quarantine_items', type_='unique')
    op.drop_index(op.f('ix_quarantine_items_ingestion_row_id'), table_name='quarantine_items')
    op.create_index(op.f('ix_quarantine_items_ingestion_row_id'), 'quarantine_items', ['ingestion_row_id'], unique=True)
    op.drop_constraint(op.f('usuarios_username_key'), 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=False)
    op.create_unique_constraint(op.f('usuarios_username_key'), 'usuarios', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_quarantine_items_ingestion_row_id'), table_name='quarantine_items')
    op.create_index(op.f('ix_quarantine_items_ingestion_row_id'), 'quarantine_items', ['ingestion_row_id'], unique=False)
    op.create_unique_constraint(op.f('uq_quarantine_items_ingestion_row_id'), 'quarantine_items', ['ingestion_row_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_ingestion_rows_ingestion_file_member_id_linha_origem'), 'ingestion_rows', ['ingestion_file_member_id', 'linha_origem'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_ingestion_files_source_url_content_sha256'), 'ingestion_files', ['source_url', 'content_sha256'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_ingestion_file_members_ingestion_file_id_member_name'), 'ingestion_file_members', ['ingestion_file_id', 'member_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_companhias_codigo_cvm'), table_name='companhias')
    op.create_index(op.f('ix_companhias_codigo_cvm'), 'companhias', ['codigo_cvm'], unique=False)
    op.drop_index(op.f('ix_companhias_cnpj_companhia'), table_name='companhias')
    op.create_index(op.f('ix_companhias_cnpj_companhia'), 'companhias', ['cnpj_companhia'], unique=False)
    op.create_unique_constraint(op.f('companhias_codigo_cvm_key'), 'companhias', ['codigo_cvm'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('companhias_cnpj_companhia_key'), 'companhias', ['cnpj_companhia'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_companhia_identificadores_valor_normalizado'), 'companhia_identificadores', ['valor_normalizado'], unique=False)
    op.create_index(op.f('ix_companhia_identificadores_tipo'), 'companhia_identificadores', ['tipo'], unique=False)
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_versao'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_relacao_emissor'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_parte_relacionada'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_id_documento'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_data_referencia'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_companhia_id'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_cnpj_companhia'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_transacoes_partes_relacionadas_ano_origem'), table_name='fre_transacoes_partes_relacionadas')
    op.drop_table('fre_transacoes_partes_relacionadas')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_versao'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_tipo_relacao'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_nome_pessoa_relacionada'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_nome_administrador'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_id_documento'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_data_referencia'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_companhia_id'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_cnpj_companhia'), table_name='fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_subordinacao_ano_origem'), table_name='fre_relacoes_subordinacao')
    op.drop_table('fre_relacoes_subordinacao')
    op.drop_index(op.f('ix_fre_relacoes_familiares_versao'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_tipo_parentesco'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_nome_pessoa_relacionada'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_nome_administrador'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_id_documento'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_data_referencia'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_companhia_id'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_cnpj_companhia'), table_name='fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_relacoes_familiares_ano_origem'), table_name='fre_relacoes_familiares')
    op.drop_table('fre_relacoes_familiares')
    op.drop_index(op.f('ix_fre_membros_comites_versao'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_tipo_comite'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_nome'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_id_documento'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_data_referencia'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_companhia_id'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_cnpj_companhia'), table_name='fre_membros_comites')
    op.drop_index(op.f('ix_fre_membros_comites_ano_origem'), table_name='fre_membros_comites')
    op.drop_table('fre_membros_comites')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_versao'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_nome'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_id_documento'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_data_referencia'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_companhia_id'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_cnpj_companhia'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_index(op.f('ix_fre_administradores_membros_conselho_fiscal_ano_origem'), table_name='fre_administradores_membros_conselho_fiscal')
    op.drop_table('fre_administradores_membros_conselho_fiscal')
    # ### end Alembic commands ###
