"""widen_fre_numeric_percentual_columns

Revision ID: dddfeda1b4b7
Revises: 740943af5883
Create Date: 2026-06-09 01:47:40.058600
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dddfeda1b4b7"
down_revision: str | None = "740943af5883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_distribuicao_capital', 'percentual_acoes_ordinarias_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'percentual_acoes_preferenciais_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'percentual_total_acoes_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'percentual_acoes_preferenciais_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_acao_ordinaria_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_acao_preferencial_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_total_acoes_circulacao',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'percentual_acoes',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    op.alter_column('fre_remuneracoes_acoes', 'diluicao_potencial',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=38, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_remuneracoes_acoes', 'diluicao_potencial',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias_classes_acoes', 'percentual_acoes',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_total_acoes_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_acao_preferencial_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_posicoes_acionarias', 'percentual_acao_ordinaria_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital_classes_acoes', 'percentual_acoes_preferenciais_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'percentual_total_acoes_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'percentual_acoes_preferenciais_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('fre_distribuicao_capital', 'percentual_acoes_ordinarias_circulacao',
               existing_type=sa.Numeric(precision=38, scale=10),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###
