"""expand_fre_relacoes_familiares_and_subordinacao_natural_keys

Revision ID: e768d8885a52
Revises: cfcc31a7815b
Create Date: 2026-06-15 23:30:39.376738
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e768d8885a52'
down_revision: Union[str, None] = 'cfcc31a7815b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_fre_relacoes_familiares_chave_natural'), 'fre_relacoes_familiares', type_='unique')
    op.create_unique_constraint('uq_fre_relacoes_familiares_chave_natural', 'fre_relacoes_familiares', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_parentesco', 'cnpj_emissor_pessoa_relacionada', 'nome_emissor_pessoa_relacionada', 'cargo_Pessoa_relacionada', 'cnpj_emissor', 'nome_emissor', 'cargo_administrador'])
    op.drop_constraint(op.f('uq_fre_relacoes_subordinacao_chave_natural'), 'fre_relacoes_subordinacao', type_='unique')
    op.create_unique_constraint('uq_fre_relacoes_subordinacao_chave_natural', 'fre_relacoes_subordinacao', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'data_inicio_exercicio_social', 'data_fim_exercicio_social', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_relacao', 'cargo_administrador', 'cargo_pessoa_relacionada'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fre_relacoes_subordinacao_chave_natural', 'fre_relacoes_subordinacao', type_='unique')
    op.create_unique_constraint(op.f('uq_fre_relacoes_subordinacao_chave_natural'), 'fre_relacoes_subordinacao', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'data_inicio_exercicio_social', 'data_fim_exercicio_social', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_relacao'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_fre_relacoes_familiares_chave_natural', 'fre_relacoes_familiares', type_='unique')
    op.create_unique_constraint(op.f('uq_fre_relacoes_familiares_chave_natural'), 'fre_relacoes_familiares', ['id_documento', 'versao', 'data_referencia', 'cnpj_companhia', 'nome_administrador', 'nome_pessoa_relacionada', 'tipo_parentesco', 'cnpj_emissor_pessoa_relacionada', 'nome_emissor_pessoa_relacionada', 'cargo_Pessoa_relacionada'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
