"""alter_fre_transacao_parte_relacionada_to_text

Revision ID: f080f52966a3
Revises: 5fea16beb6da
Create Date: 2026-06-11 14:40:22.202798
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f080f52966a3'
down_revision: str | None = '5fea16beb6da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_transacoes_partes_relacionadas', 'parte_relacionada',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('fre_transacoes_partes_relacionadas', 'relacao_emissor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'duracao_transacao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'emprestimo_divida',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'posicao_contratual_emissor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fre_transacoes_partes_relacionadas', 'posicao_contratual_emissor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'emprestimo_divida',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'duracao_transacao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'relacao_emissor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('fre_transacoes_partes_relacionadas', 'parte_relacionada',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
