"""split_zip_ingestion

Revision ID: f484cf28f893
Revises: b1f0c8f4b7aa
Create Date: 2026-06-09 22:43:31.327465
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f484cf28f893'
down_revision: str | None = 'b1f0c8f4b7aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_file_member_payloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['execucoes_sincronizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('execucoes_sincronizacao', sa.Column('parent_execucao_id', sa.Uuid(), nullable=True))
    op.add_column(
        'execucoes_sincronizacao',
        sa.Column('tipo_execucao', sa.String(length=20), nullable=False, server_default='arquivo_simples')
    )
    op.create_index(
        'idx_execucoes_sinc_composite',
        'execucoes_sincronizacao',
        ['tipo_fonte', 'ano', 'parent_execucao_id'],
        unique=False
    )
    op.create_index(
        'idx_execucoes_sinc_parent_exec_id',
        'execucoes_sincronizacao',
        ['parent_execucao_id'],
        unique=False
    )
    op.create_index(op.f('ix_execucoes_sincronizacao_status'), 'execucoes_sincronizacao', ['status'], unique=False)
    op.create_index(
        op.f('ix_execucoes_sincronizacao_tipo_execucao'),
        'execucoes_sincronizacao',
        ['tipo_execucao'],
        unique=False
    )
    op.create_foreign_key(
        'fk_execucoes_sincronizacao_parent_id',
        'execucoes_sincronizacao',
        'execucoes_sincronizacao',
        ['parent_execucao_id'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_execucoes_sincronizacao_parent_id', 'execucoes_sincronizacao', type_='foreignkey')
    op.drop_index(op.f('ix_execucoes_sincronizacao_tipo_execucao'), table_name='execucoes_sincronizacao')
    op.drop_index(op.f('ix_execucoes_sincronizacao_status'), table_name='execucoes_sincronizacao')
    op.drop_index('idx_execucoes_sinc_parent_exec_id', table_name='execucoes_sincronizacao')
    op.drop_index('idx_execucoes_sinc_composite', table_name='execucoes_sincronizacao')
    op.drop_column('execucoes_sincronizacao', 'tipo_execucao')
    op.drop_column('execucoes_sincronizacao', 'parent_execucao_id')
    op.drop_table('ingestion_file_member_payloads')
    # ### end Alembic commands ###
