from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from app.services.financeiro_mapas import arquivos_demonstracao

FonteChave = Literal["cadastro", "dfp", "itr", "fre", "fca", "ipe", "cgvn", "vlmo"]
TipoDistribuicao = Literal["csv_unico", "zip_anual"]
StatusSuporte = Literal["suportado", "pendente_mapeamento"]


@dataclass(frozen=True)
class DatasetFonte:
    dataset: str
    descricao: str
    member_name_template: str
    row_kind: str | None
    destino_promovido: str | None
    obrigatorio: bool
    status_suporte: StatusSuporte
    normalizador: str | None
    chaves_relacao: tuple[str, ...]
    observacoes: str | None = None

    def render_member_name(self, *, ano: int | None) -> str:
        if "{ano}" in self.member_name_template:
            if ano is None:
                raise ValueError("ano_obrigatorio_para_member_template")
            return self.member_name_template.format(ano=ano)
        return self.member_name_template


@dataclass(frozen=True)
class FonteRegistry:
    fonte: FonteChave
    familia: str
    descricao: str
    tipo_distribuicao: TipoDistribuicao
    dataset_path_template: str
    arquivo_principal_template: str
    primeiro_ano: int | None
    ultimo_ano: int | None
    obrigatorio: bool
    status_suporte: StatusSuporte
    dependencias: tuple[FonteChave, ...]
    datasets: tuple[DatasetFonte, ...]

    @property
    def total_datasets(self) -> int:
        return len(self.datasets)

    @property
    def datasets_obrigatorios(self) -> int:
        return sum(1 for item in self.datasets if item.obrigatorio)

    @property
    def datasets_opcionais(self) -> int:
        return sum(1 for item in self.datasets if not item.obrigatorio)

    def render_arquivo_principal(self, *, ano: int | None) -> str:
        if "{ano}" in self.arquivo_principal_template:
            if ano is None:
                raise ValueError("ano_obrigatorio_para_arquivo_principal")
            return self.arquivo_principal_template.format(ano=ano)
        return self.arquivo_principal_template


def _datasets_financeiro(prefixo: Literal["dfp", "itr"]) -> tuple[DatasetFonte, ...]:
    datasets = [
        DatasetFonte(
            dataset="documento_principal",
            descricao=f"Cabecalho documental {prefixo.upper()}",
            member_name_template=f"{prefixo}_cia_aberta_{{ano}}.csv",
            row_kind=f"{prefixo}_documento",
            destino_promovido="documentos_financeiros",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_financeiro_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento"),
            observacoes="Arquivo base do pacote anual; deve ser processado antes dos membros dependentes.",
        ),
        DatasetFonte(
            dataset="composicao_capital",
            descricao=f"Composicao de capital {prefixo.upper()}",
            member_name_template=f"{prefixo}_cia_aberta_composicao_capital_{{ano}}.csv",
            row_kind=f"{prefixo}_composicao_capital",
            destino_promovido="composicoes_capital",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_financeiro_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="parecer",
            descricao=f"Pareceres e declaracoes {prefixo.upper()}",
            member_name_template=f"{prefixo}_cia_aberta_parecer_{{ano}}.csv",
            row_kind=f"{prefixo}_parecer",
            destino_promovido="pareceres_financeiros",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_financeiro_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
    ]
    for nome_arquivo, tipo_demonstracao, escopo in arquivos_demonstracao(prefixo, 2025):
        datasets.append(
            DatasetFonte(
                dataset=f"demonstracao_{tipo_demonstracao.lower()}_{escopo.lower()}",
                descricao=f"Demonstracao {tipo_demonstracao} {escopo} {prefixo.upper()}",
                member_name_template=nome_arquivo.replace("2025", "{ano}"),
                row_kind=f"{prefixo}_demonstracao",
                destino_promovido="demonstracoes_financeiras",
                obrigatorio=True,
                status_suporte="suportado",
                normalizador="normalizar_financeiro_row",
                chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento"),
                observacoes=f"Tipo demonstracao={tipo_demonstracao}; escopo={escopo}.",
            )
        )
    return tuple(datasets)


def _datasets_fre() -> tuple[DatasetFonte, ...]:
    return (
        DatasetFonte(
            dataset="documentos",
            descricao="Cabecalho documental do FRE",
            member_name_template="fre_cia_aberta_{ano}.csv",
            row_kind="fre_documento",
            destino_promovido="fre_documentos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento"),
            observacoes="Processar primeiro para abastecer header_map de linhas filhas.",
        ),
        DatasetFonte(
            dataset="auditores",
            descricao="Informacoes de auditoria do FRE",
            member_name_template="fre_cia_aberta_auditor_{ano}.csv",
            row_kind="fre_auditor",
            destino_promovido="fre_auditores",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="capital_social",
            descricao="Capital social declarado no FRE",
            member_name_template="fre_cia_aberta_capital_social_{ano}.csv",
            row_kind="fre_capital_social",
            destino_promovido="fre_capital_social",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="posicao_acionaria",
            descricao="Posicao acionaria do FRE",
            member_name_template="fre_cia_aberta_posicao_acionaria_{ano}.csv",
            row_kind="fre_posicao_acionaria",
            destino_promovido="fre_posicoes_acionarias",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="remuneracao_total_orgao",
            descricao="Remuneracao total por orgao do FRE",
            member_name_template="fre_cia_aberta_remuneracao_total_orgao_{ano}.csv",
            row_kind="fre_remuneracao_total_orgao",
            destino_promovido="fre_remuneracoes_totais_orgaos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="empregado_posicao_genero",
            descricao="Empregados por posicao e genero no FRE",
            member_name_template="fre_cia_aberta_empregado_posicao_declaracao_genero_{ano}.csv",
            row_kind="fre_empregado_posicao_genero",
            destino_promovido="fre_empregados_posicao_genero",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes="Membro opcional no MVP atual.",
        ),
        DatasetFonte(
            dataset="responsavel",
            descricao="Pessoas responsaveis pelo FRE",
            member_name_template="fre_cia_aberta_responsavel_{ano}.csv",
            row_kind="fre_responsavel",
            destino_promovido="fre_responsaveis",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="capital_social_classe_acao",
            descricao="Classes de acoes do capital social",
            member_name_template="fre_cia_aberta_capital_social_classe_acao_{ano}.csv",
            row_kind="fre_capital_social_classe_acao",
            destino_promovido="fre_capital_social_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="capital_social_titulo_conversivel",
            descricao="Titulos conversiveis do capital social",
            member_name_template="fre_cia_aberta_capital_social_titulo_conversivel_{ano}.csv",
            row_kind="fre_capital_social_titulo_conversivel",
            destino_promovido="fre_capital_social_titulos_conversiveis",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="distribuicao_capital",
            descricao="Distribuicao de capital no FRE",
            member_name_template="fre_cia_aberta_distribuicao_capital_{ano}.csv",
            row_kind="fre_distribuicao_capital",
            destino_promovido="fre_distribuicao_capital",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="distribuicao_capital_classe_acao",
            descricao="Classes de acoes da distribuicao de capital",
            member_name_template="fre_cia_aberta_distribuicao_capital_classe_acao_{ano}.csv",
            row_kind="fre_distribuicao_capital_classe_acao",
            destino_promovido="fre_distribuicao_capital_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="posicao_acionaria_classe_acao",
            descricao="Classes de acoes da posicao acionaria",
            member_name_template="fre_cia_aberta_posicao_acionaria_classe_acao_{ano}.csv",
            row_kind="fre_posicao_acionaria_classe_acao",
            destino_promovido="fre_posicoes_acionarias_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="remuneracao_maxima_minima_media",
            descricao="Remuneracao maxima, minima e media do FRE",
            member_name_template="fre_cia_aberta_remuneracao_maxima_minima_media_{ano}.csv",
            row_kind="fre_remuneracao_maxima_minima_media",
            destino_promovido="fre_remuneracoes_maximas_minimas_medias",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="remuneracao_variavel",
            descricao="Remuneracao variavel do FRE",
            member_name_template="fre_cia_aberta_remuneracao_variavel_{ano}.csv",
            row_kind="fre_remuneracao_variavel",
            destino_promovido="fre_remuneracoes_variaveis",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="remuneracao_acao",
            descricao="Remuneracao baseada em acoes do FRE",
            member_name_template="fre_cia_aberta_remuneracao_acao_{ano}.csv",
            row_kind="fre_remuneracao_acao",
            destino_promovido="fre_remuneracoes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="acao_entregue",
            descricao="Acoes entregues do FRE",
            member_name_template="fre_cia_aberta_acao_entregue_{ano}.csv",
            row_kind="fre_acao_entregue",
            destino_promovido="fre_acoes_entregues",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="auditor_responsavel",
            descricao="Auditores responsaveis do FRE",
            member_name_template="fre_cia_aberta_auditor_responsavel_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="informacao_financeira",
            descricao="Informacoes financeiras do FRE",
            member_name_template="fre_cia_aberta_informacao_financeira_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="distribuicao_dividendos",
            descricao="Distribuicao de dividendos do FRE",
            member_name_template="fre_cia_aberta_distribuicao_dividendos_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="distribuicao_dividendos_classe_acao",
            descricao="Classes de acoes na distribuicao de dividendos",
            member_name_template="fre_cia_aberta_distribuicao_dividendos_classe_acao_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="endividamento",
            descricao="Endividamento do emissor no FRE",
            member_name_template="fre_cia_aberta_endividamento_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="obrigacao",
            descricao="Obrigacoes do emissor no FRE",
            member_name_template="fre_cia_aberta_obrigacao_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="historico_emissor",
            descricao="Historico do emissor no FRE",
            member_name_template="fre_cia_aberta_historico_emissor_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="grupo_economico_reestruturacao",
            descricao="Grupo economico e reestruturacoes no FRE",
            member_name_template="fre_cia_aberta_grupo_economico_reestruturacao_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="ativo_imobilizado",
            descricao="Ativos imobilizados do FRE",
            member_name_template="fre_cia_aberta_ativo_imobilizado_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="ativo_intangivel",
            descricao="Ativos intangiveis do FRE",
            member_name_template="fre_cia_aberta_ativo_intangivel_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="participacao_sociedade",
            descricao="Participacoes em sociedades no FRE",
            member_name_template="fre_cia_aberta_participacao_sociedade_{ano}.csv",
            row_kind="fre_participacao_sociedade",
            destino_promovido="fre_participacoes_sociedades",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="participacao_sociedade_valorizacao_acao",
            descricao="Valorizacao de acoes em participacoes no FRE",
            member_name_template="fre_cia_aberta_participacao_sociedade_valorizacao_acao_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="administrador_membro_conselho_fiscal",
            descricao="Membros do conselho fiscal e administradores no FRE",
            member_name_template="fre_cia_aberta_administrador_membro_conselho_fiscal_{ano}.csv",
            row_kind="fre_administrador_membro_conselho_fiscal",
            destino_promovido="fre_administradores_membros_conselho_fiscal",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="membro_comite",
            descricao="Membros de comites no FRE",
            member_name_template="fre_cia_aberta_membro_comite_{ano}.csv",
            row_kind="fre_membro_comite",
            destino_promovido="fre_membros_comites",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="relacao_familiar",
            descricao="Relacoes familiares declaradas no FRE",
            member_name_template="fre_cia_aberta_relacao_familiar_{ano}.csv",
            row_kind="fre_relacao_familiar",
            destino_promovido="fre_relacoes_familiares",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="relacao_subordinacao",
            descricao="Relacoes de subordinacao declaradas no FRE",
            member_name_template="fre_cia_aberta_relacao_subordinacao_{ano}.csv",
            row_kind="fre_relacao_subordinacao",
            destino_promovido="fre_relacoes_subordinacao",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="transacao_parte_relacionada",
            descricao="Transacoes com partes relacionadas no FRE",
            member_name_template="fre_cia_aberta_transacao_parte_relacionada_{ano}.csv",
            row_kind="fre_transacao_parte_relacionada",
            destino_promovido="fre_transacoes_partes_relacionadas",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_aumento",
            descricao="Aumentos de capital social no FRE",
            member_name_template="fre_cia_aberta_capital_social_aumento_{ano}.csv",
            row_kind="fre_capital_social_aumento",
            destino_promovido="fre_capital_social_aumentos",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_aumento_classe_acao",
            descricao="Classes de acoes nos aumentos de capital social",
            member_name_template="fre_cia_aberta_capital_social_aumento_classe_acao_{ano}.csv",
            row_kind="fre_capital_social_aumento_classe_acao",
            destino_promovido="fre_capital_social_aumento_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_desdobramento",
            descricao="Desdobramentos de capital social no FRE",
            member_name_template="fre_cia_aberta_capital_social_desdobramento_{ano}.csv",
            row_kind="fre_capital_social_desdobramento",
            destino_promovido="fre_capital_social_desdobramentos",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_desdobramento_classe_acao",
            descricao="Classes de acoes nos desdobramentos de capital social",
            member_name_template="fre_cia_aberta_capital_social_desdobramento_classe_acao_{ano}.csv",
            row_kind="fre_capital_social_desdobramento_classe_acao",
            destino_promovido="fre_capital_social_desdobramento_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_reducao",
            descricao="Reducoes de capital social no FRE",
            member_name_template="fre_cia_aberta_capital_social_reducao_{ano}.csv",
            row_kind="fre_capital_social_reducao",
            destino_promovido="fre_capital_social_reducoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="capital_social_reducao_classe_acao",
            descricao="Classes de acoes nas reducoes de capital social",
            member_name_template="fre_cia_aberta_capital_social_reducao_classe_acao_{ano}.csv",
            row_kind="fre_capital_social_reducao_classe_acao",
            destino_promovido="fre_capital_social_reducao_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="direito_acao",
            descricao="Direitos de acoes declarados no FRE",
            member_name_template="fre_cia_aberta_direito_acao_{ano}.csv",
            row_kind="fre_direito_acao",
            destino_promovido="fre_direitos_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="volume_valor_mobiliario",
            descricao="Volume de valores mobiliarios no FRE",
            member_name_template="fre_cia_aberta_volume_valor_mobiliario_{ano}.csv",
            row_kind="fre_volume_valor_mobiliario",
            destino_promovido="fre_volumes_valores_mobiliarios",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="outro_valor_mobiliario",
            descricao="Outros valores mobiliarios no FRE",
            member_name_template="fre_cia_aberta_outro_valor_mobiliario_{ano}.csv",
            row_kind="fre_outro_valor_mobiliario",
            destino_promovido="fre_outros_valores_mobiliarios",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="titular_valor_mobiliario",
            descricao="Titulares de valores mobiliarios no FRE",
            member_name_template="fre_cia_aberta_titular_valor_mobiliario_{ano}.csv",
            row_kind="fre_titular_valor_mobiliario",
            destino_promovido="fre_titulares_valores_mobiliarios",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="mercado_estrangeiro",
            descricao="Mercados estrangeiros declarados no FRE",
            member_name_template="fre_cia_aberta_mercado_estrangeiro_{ano}.csv",
            row_kind="fre_mercado_estrangeiro",
            destino_promovido="fre_mercados_estrangeiros",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="titulo_exterior",
            descricao="Titulos emitidos no exterior no FRE",
            member_name_template="fre_cia_aberta_titulo_exterior_{ano}.csv",
            row_kind="fre_titulo_exterior",
            destino_promovido="fre_titulos_exterior",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="plano_recompra",
            descricao="Planos de recompra de acoes no FRE",
            member_name_template="fre_cia_aberta_plano_recompra_{ano}.csv",
            row_kind="fre_plano_recompra",
            destino_promovido="fre_planos_recompra",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="plano_recompra_classe_acao",
            descricao="Classes de acoes nos planos de recompra",
            member_name_template="fre_cia_aberta_plano_recompra_classe_acao_{ano}.csv",
            row_kind="fre_plano_recompra_classe_acao",
            destino_promovido="fre_plano_recompra_classes_acoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="valor_mobiliario_tesouraria_movimentacao",
            descricao="Movimentacoes de valores mobiliarios em tesouraria",
            member_name_template="fre_cia_aberta_valor_mobiliario_tesouraria_movimentacao_{ano}.csv",
            row_kind="fre_valor_mobiliario_tesouraria_movimentacao",
            destino_promovido="fre_valores_mobiliarios_tesouraria_movimentacoes",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="valor_mobiliario_tesouraria_ultimo_exercicio",
            descricao="Ultimo exercicio de valores mobiliarios em tesouraria",
            member_name_template="fre_cia_aberta_valor_mobiliario_tesouraria_ultimo_exercicio_{ano}.csv",
            row_kind="fre_valor_mobiliario_tesouraria_ultimo_exercicio",
            destino_promovido="fre_valores_mobiliarios_tesouraria_ultimos_exercicios",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="politica_negociacao",
            descricao="Politica de negociacao no FRE",
            member_name_template="fre_cia_aberta_politica_negociacao_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="politica_negociacao_cargo",
            descricao="Cargos e politicas de negociacao no FRE",
            member_name_template="fre_cia_aberta_politica_negociacao_cargo_{ano}.csv",
            row_kind=None,
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="pendente_mapeamento",
            normalizador=None,
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="administrador_pcd",
            descricao="Declaracao PCD dos administradores",
            member_name_template="fre_cia_aberta_administrador_PCD_{ano}.csv",
            row_kind="fre_administrador_pcd",
            destino_promovido="fre_administradores_pcd",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="administrador_declaracao_genero",
            descricao="Declaracao de genero dos administradores",
            member_name_template="fre_cia_aberta_administrador_declaracao_genero_{ano}.csv",
            row_kind="fre_administrador_declaracao_genero",
            destino_promovido="fre_administradores_declaracao_genero",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="administrador_declaracao_raca",
            descricao="Declaracao de raca dos administradores",
            member_name_template="fre_cia_aberta_administrador_declaracao_raca_{ano}.csv",
            row_kind="fre_administrador_declaracao_raca",
            destino_promovido="fre_administradores_declaracao_raca",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_posicao_declaracao_raca",
            descricao="Declaracao de raca por posicao de empregados",
            member_name_template="fre_cia_aberta_empregado_posicao_declaracao_raca_{ano}.csv",
            row_kind="fre_empregado_posicao_declaracao_raca",
            destino_promovido="fre_empregados_posicao_declaracao_raca",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_posicao_faixa_etaria",
            descricao="Faixa etaria por posicao de empregados",
            member_name_template="fre_cia_aberta_empregado_posicao_faixa_etaria_{ano}.csv",
            row_kind="fre_empregado_posicao_faixa_etaria",
            destino_promovido="fre_empregados_posicao_faixa_etaria",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_posicao_local",
            descricao="Localizacao por posicao de empregados",
            member_name_template="fre_cia_aberta_empregado_posicao_local_{ano}.csv",
            row_kind="fre_empregado_posicao_local",
            destino_promovido="fre_empregados_posicao_local",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_pcd",
            descricao="PCD por posicao de empregados",
            member_name_template="fre_cia_aberta_empregado_PCD_{ano}.csv",
            row_kind="fre_empregado_pcd",
            destino_promovido="fre_empregados_pcd",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_local_declaracao_genero",
            descricao="Declaracao de genero por localizacao de empregados",
            member_name_template="fre_cia_aberta_empregado_local_declaracao_genero_{ano}.csv",
            row_kind="fre_empregado_local_declaracao_genero",
            destino_promovido="fre_empregados_local_declaracao_genero",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_local_declaracao_raca",
            descricao="Declaracao de raca por localizacao de empregados",
            member_name_template="fre_cia_aberta_empregado_local_declaracao_raca_{ano}.csv",
            row_kind="fre_empregado_local_declaracao_raca",
            destino_promovido="fre_empregados_local_declaracao_raca",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
        DatasetFonte(
            dataset="empregado_local_faixa_etaria",
            descricao="Faixa etaria por localizacao de empregados",
            member_name_template="fre_cia_aberta_empregado_local_faixa_etaria_{ano}.csv",
            row_kind="fre_empregado_local_faixa_etaria",
            destino_promovido="fre_empregados_local_faixa_etaria",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fre_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
        ),
    )


def _datasets_fca() -> tuple[DatasetFonte, ...]:
    return (
        DatasetFonte(
            dataset="original",
            descricao="Cabecalho documental do FCA",
            member_name_template="fca_cia_aberta_{ano}.csv",
            row_kind="fca_documento",
            destino_promovido="fca_documentos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento"),
            observacoes="Processar primeiro para ancorar membros filhos do mesmo documento.",
        ),
        DatasetFonte(
            dataset="geral",
            descricao="Dados gerais do formulario cadastral",
            member_name_template="fca_cia_aberta_geral_{ano}.csv",
            row_kind="fca_geral",
            destino_promovido="fca_geral",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="endereco",
            descricao="Enderecos declarados no FCA",
            member_name_template="fca_cia_aberta_endereco_{ano}.csv",
            row_kind="fca_endereco",
            destino_promovido="fca_enderecos",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="dri",
            descricao="Diretor de relacoes com investidores",
            member_name_template="fca_cia_aberta_dri_{ano}.csv",
            row_kind="fca_dri",
            destino_promovido="fca_dri",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="auditor",
            descricao="Auditoria independente do FCA",
            member_name_template="fca_cia_aberta_auditor_{ano}.csv",
            row_kind="fca_auditor",
            destino_promovido="fca_auditores",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="valor_mobiliario",
            descricao="Valores mobiliarios negociados",
            member_name_template="fca_cia_aberta_valor_mobiliario_{ano}.csv",
            row_kind="fca_valor_mobiliario",
            destino_promovido="fca_valores_mobiliarios",
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes=None,
        ),
        DatasetFonte(
            dataset="escriturador",
            descricao="Escriturador de acoes",
            member_name_template="fca_cia_aberta_escriturador_{ano}.csv",
            row_kind="fca_escriturador",
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes="Suporte atual apenas em staging.",
        ),
        DatasetFonte(
            dataset="canal_divulgacao",
            descricao="Canais de divulgacao",
            member_name_template="fca_cia_aberta_canal_divulgacao_{ano}.csv",
            row_kind="fca_canal_divulgacao",
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes="Suporte atual apenas em staging.",
        ),
        DatasetFonte(
            dataset="departamento_acionistas",
            descricao="Departamento de acionistas",
            member_name_template="fca_cia_aberta_departamento_acionistas_{ano}.csv",
            row_kind="fca_departamento_acionistas",
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes="Suporte atual apenas em staging.",
        ),
        DatasetFonte(
            dataset="pais_estrangeiro_negociacao",
            descricao="Paises estrangeiros de negociacao",
            member_name_template="fca_cia_aberta_pais_estrangeiro_negociacao_{ano}.csv",
            row_kind="fca_pais_estrangeiro_negociacao",
            destino_promovido=None,
            obrigatorio=False,
            status_suporte="suportado",
            normalizador="normalizar_fca_row",
            chaves_relacao=("cnpj_companhia", "id_documento"),
            observacoes="Suporte atual apenas em staging.",
        ),
    )


def _datasets_ipe() -> tuple[DatasetFonte, ...]:
    return (
        DatasetFonte(
            dataset="original",
            descricao="Documento principal do IPE",
            member_name_template="ipe_cia_aberta_{ano}.csv",
            row_kind="ipe_documento",
            destino_promovido="ipe_documentos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_ipe_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "protocolo_entrega"),
            observacoes="Arquivo unico do pacote anual IPE; deve ser processado primeiro.",
        ),
    )


def _datasets_vlmo() -> tuple[DatasetFonte, ...]:
    return (
        DatasetFonte(
            dataset="original",
            descricao="Documento principal do VLMO",
            member_name_template="vlmo_cia_aberta_{ano}.csv",
            row_kind="vlmo_documento",
            destino_promovido="vlmo_documentos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_vlmo_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "protocolo_entrega"),
            observacoes="Processar primeiro para ancorar versao e cabecalho documental do pacote.",
        ),
        DatasetFonte(
            dataset="consolidado",
            descricao="Posicoes e movimentacoes consolidadas do VLMO",
            member_name_template="vlmo_cia_aberta_con_{ano}.csv",
            row_kind="vlmo_consolidado",
            destino_promovido="vlmo_consolidado",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_vlmo_row",
            chaves_relacao=("cnpj_companhia", "data_referencia", "versao"),
            observacoes="Cobertura consolidada de valores mobiliarios negociados e detidos.",
        ),
    )


def _datasets_cgvn() -> tuple[DatasetFonte, ...]:
    return (
        DatasetFonte(
            dataset="original",
            descricao="Documento principal do CGVN",
            member_name_template="cgvn_cia_aberta_{ano}.csv",
            row_kind="cgvn_documento",
            destino_promovido="cgvn_documentos",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_cgvn_row",
            chaves_relacao=("cnpj_companhia", "codigo_cvm", "id_documento", "versao"),
            observacoes="Cabecalho documental e dados gerais do informe de governanca corporativa.",
        ),
        DatasetFonte(
            dataset="praticas",
            descricao="Praticas adotadas e justificativas do CGVN",
            member_name_template="cgvn_cia_aberta_praticas_{ano}.csv",
            row_kind="cgvn_pratica",
            destino_promovido="cgvn_praticas",
            obrigatorio=True,
            status_suporte="suportado",
            normalizador="normalizar_cgvn_row",
            chaves_relacao=("cnpj_companhia", "data_referencia", "versao", "id_item", "linha_origem"),
            observacoes="Adesao aos principios de governanca corporativa com explicacoes detalhadas.",
        ),
    )


_FONTES: tuple[FonteRegistry, ...] = (
    FonteRegistry(
        fonte="cadastro",
        familia="cadastro_cvm",
        descricao="Base cadastral de companhias abertas e emissor estrangeiro.",
        tipo_distribuicao="csv_unico",
        dataset_path_template="CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv",
        arquivo_principal_template="cad_cia_aberta.csv",
        primeiro_ano=None,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=(),
        datasets=(
            DatasetFonte(
                dataset="cadastro_aberta",
                descricao="Cadastro base de companhias abertas",
                member_name_template="cad_cia_aberta.csv",
                row_kind="cadastro_registro_cvm",
                destino_promovido="companhias",
                obrigatorio=True,
                status_suporte="suportado",
                normalizador="normalizar_linha_cadastro",
                chaves_relacao=("cnpj_companhia", "codigo_cvm"),
                observacoes="Raiz de identidade do dominio.",
            ),
            DatasetFonte(
                dataset="cadastro_estrangeira",
                descricao="Cadastro de emissor estrangeiro relacionado",
                member_name_template="cad_cia_estrang.csv",
                row_kind="cadastro_registro_cvm",
                destino_promovido="companhias",
                obrigatorio=True,
                status_suporte="suportado",
                normalizador="normalizar_linha_cadastro_estrangeira",
                chaves_relacao=("cnpj_companhia", "codigo_cvm"),
                observacoes="Complementa malha de identidade para documentos ancorados fora do cadastro aberto.",
            ),
        ),
    ),
    FonteRegistry(
        fonte="dfp",
        familia="documentos_financeiros",
        descricao="Pacote anual DFP com cabecalho, demonstracoes, parecer e composicao de capital.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/DFP/DADOS/dfp_cia_aberta_{ano}.zip",
        arquivo_principal_template="dfp_cia_aberta_{ano}.zip",
        primeiro_ano=2010,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_financeiro("dfp"),
    ),
    FonteRegistry(
        fonte="itr",
        familia="documentos_financeiros",
        descricao="Pacote anual ITR com cabecalho, demonstracoes, parecer e composicao de capital.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/ITR/DADOS/itr_cia_aberta_{ano}.zip",
        arquivo_principal_template="itr_cia_aberta_{ano}.zip",
        primeiro_ano=2010,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_financeiro("itr"),
    ),
    FonteRegistry(
        fonte="fre",
        familia="formulario_referencia",
        descricao="Pacote anual FRE MVP com cabecalho e cinco grupos filhos promovidos.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/FRE/DADOS/fre_cia_aberta_{ano}.zip",
        arquivo_principal_template="fre_cia_aberta_{ano}.zip",
        primeiro_ano=2010,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_fre(),
    ),
    FonteRegistry(
        fonte="fca",
        familia="formulario_cadastral",
        descricao="Pacote anual FCA com promocao de datasets de maior valor e staging dos demais membros.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/FCA/DADOS/fca_cia_aberta_{ano}.zip",
        arquivo_principal_template="fca_cia_aberta_{ano}.zip",
        primeiro_ano=2010,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_fca(),
    ),
    FonteRegistry(
        fonte="ipe",
        familia="informacoes_periodicas_eventuais",
        descricao="Pacote anual IPE com documento principal promovido.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/IPE/DADOS/ipe_cia_aberta_{ano}.zip",
        arquivo_principal_template="ipe_cia_aberta_{ano}.zip",
        primeiro_ano=2003,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_ipe(),
    ),
    FonteRegistry(
        fonte="vlmo",
        familia="valores_mobiliarios_negociados_detidos",
        descricao="Pacote anual VLMO com documento principal e consolidado promovidos.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/VLMO/DADOS/vlmo_cia_aberta_{ano}.zip",
        arquivo_principal_template="vlmo_cia_aberta_{ano}.zip",
        primeiro_ano=2018,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_vlmo(),
    ),
    FonteRegistry(
        fonte="cgvn",
        familia="governanca",
        descricao="Pacote anual CGVN/ICBGC com documento principal e praticas promovidos.",
        tipo_distribuicao="zip_anual",
        dataset_path_template="CIA_ABERTA/DOC/CGVN/DADOS/cgvn_cia_aberta_{ano}.zip",
        arquivo_principal_template="cgvn_cia_aberta_{ano}.zip",
        primeiro_ano=2018,
        ultimo_ano=None,
        obrigatorio=True,
        status_suporte="suportado",
        dependencias=("cadastro",),
        datasets=_datasets_cgvn(),
    ),
)


def listar_fontes() -> list[FonteRegistry]:
    return list(_FONTES)


def fontes_implementadas() -> list[FonteRegistry]:
    return [fonte for fonte in _FONTES if fonte.status_suporte == "suportado"]


def obter_fonte(fonte: str) -> FonteRegistry | None:
    for item in _FONTES:
        if item.fonte == fonte:
            return item
    return None


def listar_datasets(fonte: str) -> list[DatasetFonte]:
    fonte_item = obter_fonte(fonte)
    return [] if fonte_item is None else list(fonte_item.datasets)


def dataset_por_row_kind(row_kind: str) -> DatasetFonte | None:
    for fonte in _FONTES:
        for dataset in fonte.datasets:
            if dataset.row_kind == row_kind:
                return dataset
    return None


def dataset_por_member_name(fonte: str, member_name: str, ano: int) -> DatasetFonte | None:
    fonte_item = obter_fonte(fonte)
    if fonte_item is None:
        return None
    for dataset in fonte_item.datasets:
        if dataset.render_member_name(ano=ano) == member_name:
            return dataset
    return None
