{{- if .Values.materializationWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tucano-cvm.fullname" . }}-materialization-worker
  labels:
    {{- include "tucano-cvm.labels" . | nindent 4 }}
    app.kubernetes.io/component: materialization-worker
spec:
  replicas: {{ .Values.materializationWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "tucano-cvm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: materialization-worker
  template:
    metadata:
      labels:
        {{- include "tucano-cvm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: materialization-worker
      {{- with .Values.materializationWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: materialization-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.materializationWorker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "tucano-cvm.configMapName" . }}
            - secretRef:
                name: {{ include "tucano-cvm.appSecretName" . }}
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tucano-cvm.appSecretName" . }}
                  key: TUCANO_CVM_TOKEN
            {{- range $key, $val := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.secretName }}
                  key: {{ $val.secretKey }}
            {{- end }}
          resources:
            {{- toYaml .Values.materializationWorker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
