{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tucano-cvm.fullname" . }}-migration-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "tucano-cvm.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "tucano-cvm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "tucano-cvm.configMapName" . }}
            - secretRef:
                name: {{ include "tucano-cvm.appSecretName" . }}
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tucano-cvm.appSecretName" . }}
                  key: TUCANO_CVM_TOKEN
            {{- range $key, $val := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.secretName }}
                  key: {{ $val.secretKey }}
            {{- end }}
{{- end }}
