name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'docusaurus/**'
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        run: cp .env.example .env

      - name: Build app image
        run: docker compose build cvm_api

      - name: Run tests
        run: docker compose run --rm cvm_api python -m pytest -q

      - name: Run ruff
        run: docker compose run --rm cvm_api ruff check . --ignore E501

      - name: Run mypy
        run: docker compose run --rm cvm_api mypy .
